/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { EmailrError } from "./emailrerror.js";

/**
 * Topic not found
 */
export type DeleteV1TopicsIdNotFoundErrorData = {
  error: string;
};

/**
 * Topic not found
 */
export class DeleteV1TopicsIdNotFoundError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DeleteV1TopicsIdNotFoundErrorData;

  constructor(
    err: DeleteV1TopicsIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DeleteV1TopicsIdNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type DeleteV1TopicsIdUnauthorizedErrorData = {
  error: string;
};

/**
 * Unauthorized
 */
export class DeleteV1TopicsIdUnauthorizedError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DeleteV1TopicsIdUnauthorizedErrorData;

  constructor(
    err: DeleteV1TopicsIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DeleteV1TopicsIdUnauthorizedError";
  }
}

/** @internal */
export const DeleteV1TopicsIdNotFoundError$inboundSchema: z.ZodMiniType<
  DeleteV1TopicsIdNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DeleteV1TopicsIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const DeleteV1TopicsIdUnauthorizedError$inboundSchema: z.ZodMiniType<
  DeleteV1TopicsIdUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DeleteV1TopicsIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
