/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { EmailrError } from "./emailrerror.js";

/**
 * Unauthorized
 */
export type GetV1BillingUsageUnauthorizedErrorData = {
  error: string;
};

/**
 * Unauthorized
 */
export class GetV1BillingUsageUnauthorizedError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetV1BillingUsageUnauthorizedErrorData;

  constructor(
    err: GetV1BillingUsageUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1BillingUsageUnauthorizedError";
  }
}

/** @internal */
export const GetV1BillingUsageUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetV1BillingUsageUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1BillingUsageUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
