/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { EmailrError } from "./emailrerror.js";

/**
 * Organization or contact not found
 */
export type GetV1UnsubscribeOrganizationIdNotFoundErrorData = {
  error: string;
};

/**
 * Organization or contact not found
 */
export class GetV1UnsubscribeOrganizationIdNotFoundError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetV1UnsubscribeOrganizationIdNotFoundErrorData;

  constructor(
    err: GetV1UnsubscribeOrganizationIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1UnsubscribeOrganizationIdNotFoundError";
  }
}

/** @internal */
export const GetV1UnsubscribeOrganizationIdNotFoundError$inboundSchema:
  z.ZodMiniType<GetV1UnsubscribeOrganizationIdNotFoundError, unknown> = z.pipe(
    z.object({
      error: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1UnsubscribeOrganizationIdNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
