/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { EmailrError } from "./emailrerror.js";

/**
 * Unauthorized
 */
export type PostV1BillingCheckoutUnauthorizedErrorData = {
  error: string;
};

/**
 * Unauthorized
 */
export class PostV1BillingCheckoutUnauthorizedError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PostV1BillingCheckoutUnauthorizedErrorData;

  constructor(
    err: PostV1BillingCheckoutUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostV1BillingCheckoutUnauthorizedError";
  }
}

/** @internal */
export const PostV1BillingCheckoutUnauthorizedError$inboundSchema:
  z.ZodMiniType<PostV1BillingCheckoutUnauthorizedError, unknown> = z.pipe(
    z.object({
      error: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1BillingCheckoutUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
