/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { EmailrError } from "./emailrerror.js";

/**
 * Topic not found
 */
export type PutV1TopicsIdNotFoundErrorData = {
  error: string;
};

/**
 * Topic not found
 */
export class PutV1TopicsIdNotFoundError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PutV1TopicsIdNotFoundErrorData;

  constructor(
    err: PutV1TopicsIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PutV1TopicsIdNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type PutV1TopicsIdUnauthorizedErrorData = {
  error: string;
};

/**
 * Unauthorized
 */
export class PutV1TopicsIdUnauthorizedError extends EmailrError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PutV1TopicsIdUnauthorizedErrorData;

  constructor(
    err: PutV1TopicsIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PutV1TopicsIdUnauthorizedError";
  }
}

/** @internal */
export const PutV1TopicsIdNotFoundError$inboundSchema: z.ZodMiniType<
  PutV1TopicsIdNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PutV1TopicsIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const PutV1TopicsIdUnauthorizedError$inboundSchema: z.ZodMiniType<
  PutV1TopicsIdUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PutV1TopicsIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
