/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

let value: CreateTemplateRequest = {
  name: "Welcome Email",
  subject: "Welcome to {{"{{"}}company}}",
  htmlContent: "<h1>Welcome {{"{{"}}name}}</h1>",
  textContent: "Welcome {{"{{"}}name}}",
  variables: [
    "name",
    "company",
  ],
};