/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysCreate } from "../funcs/apiKeysCreate.js";
import { apiKeysList } from "../funcs/apiKeysList.js";
import { apiKeysRevoke } from "../funcs/apiKeysRevoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApiKeys extends ClientSDK {
  /**
   * Create API key
   *
   * @remarks
   * Create a new API key for programmatic access
   */
  async create(
    request?: models.CreateApiKeyRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ApiKey> {
    return unwrapAsync(apiKeysCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List API keys
   *
   * @remarks
   * Get all active API keys (keys are not returned)
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.ApiKeyListItem>> {
    return unwrapAsync(apiKeysList(
      this,
      options,
    ));
  }

  /**
   * Revoke API key
   *
   * @remarks
   * Revoke an API key (soft delete)
   */
  async revoke(
    request: operations.RevokeApiKeyRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(apiKeysRevoke(
      this,
      request,
      options,
    ));
  }
}
