/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingGetV1BillingUsage } from "../funcs/billingGetV1BillingUsage.js";
import { billingPostV1BillingCheckout } from "../funcs/billingPostV1BillingCheckout.js";
import { billingPostV1BillingPortal } from "../funcs/billingPostV1BillingPortal.js";
import { billingPostV1BillingWebhooks } from "../funcs/billingPostV1BillingWebhooks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Billing extends ClientSDK {
  async postV1BillingCheckout(
    request?: operations.PostV1BillingCheckoutRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1BillingCheckoutResponse> {
    return unwrapAsync(billingPostV1BillingCheckout(
      this,
      request,
      options,
    ));
  }

  async postV1BillingPortal(
    options?: RequestOptions,
  ): Promise<operations.PostV1BillingPortalResponse> {
    return unwrapAsync(billingPostV1BillingPortal(
      this,
      options,
    ));
  }

  async getV1BillingUsage(
    options?: RequestOptions,
  ): Promise<operations.GetV1BillingUsageResponse> {
    return unwrapAsync(billingGetV1BillingUsage(
      this,
      options,
    ));
  }

  async postV1BillingWebhooks(
    request?: any | null | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1BillingWebhooksResponse> {
    return unwrapAsync(billingPostV1BillingWebhooks(
      this,
      request,
      options,
    ));
  }
}
