/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { broadcastsCreate } from "../funcs/broadcastsCreate.js";
import { broadcastsGet } from "../funcs/broadcastsGet.js";
import { broadcastsList } from "../funcs/broadcastsList.js";
import { broadcastsSend } from "../funcs/broadcastsSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Broadcasts extends ClientSDK {
  /**
   * Create broadcast
   *
   * @remarks
   * Create a new email broadcast campaign
   */
  async create(
    request?: models.CreateBroadcastRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Broadcast> {
    return unwrapAsync(broadcastsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List broadcasts
   *
   * @remarks
   * Get all broadcasts for your organization
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.Broadcast>> {
    return unwrapAsync(broadcastsList(
      this,
      options,
    ));
  }

  /**
   * Send broadcast
   *
   * @remarks
   * Send a broadcast to all recipients
   */
  async send(
    request: operations.SendBroadcastRequest,
    options?: RequestOptions,
  ): Promise<models.SendBroadcastResponse> {
    return unwrapAsync(broadcastsSend(
      this,
      request,
      options,
    ));
  }

  /**
   * Get broadcast
   *
   * @remarks
   * Get a specific broadcast by ID
   */
  async get(
    request: operations.GetBroadcastRequest,
    options?: RequestOptions,
  ): Promise<models.Broadcast> {
    return unwrapAsync(broadcastsGet(
      this,
      request,
      options,
    ));
  }
}
