/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsBulkCreate } from "../funcs/contactsBulkCreate.js";
import { contactsCreate } from "../funcs/contactsCreate.js";
import { contactsDelete } from "../funcs/contactsDelete.js";
import { contactsGet } from "../funcs/contactsGet.js";
import { contactsList } from "../funcs/contactsList.js";
import { contactsUpdate } from "../funcs/contactsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * Create a contact
   *
   * @remarks
   * Create a new contact in your organization
   */
  async create(
    request?: models.CreateContactRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List contacts
   *
   * @remarks
   * Get a list of contacts with optional filtering
   */
  async list(
    request?: operations.ListContactsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ContactListResponse> {
    return unwrapAsync(contactsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk create contacts
   *
   * @remarks
   * Import multiple contacts at once
   */
  async bulkCreate(
    request?: models.BulkCreateContactsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.BulkCreateContactsResponse> {
    return unwrapAsync(contactsBulkCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get contact
   *
   * @remarks
   * Get a specific contact by ID
   */
  async get(
    request: operations.GetContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update contact
   *
   * @remarks
   * Update a contact's information
   */
  async update(
    request: operations.UpdateContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete contact
   *
   * @remarks
   * Delete a contact from your organization
   */
  async delete(
    request: operations.DeleteContactRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(contactsDelete(
      this,
      request,
      options,
    ));
  }
}
