/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactSyncDeleteV1ContactSyncId } from "../funcs/contactSyncDeleteV1ContactSyncId.js";
import { contactSyncGetV1ContactSync } from "../funcs/contactSyncGetV1ContactSync.js";
import { contactSyncPostV1ContactSyncSupabase } from "../funcs/contactSyncPostV1ContactSyncSupabase.js";
import { contactSyncPostV1ContactSyncWebhookSyncId } from "../funcs/contactSyncPostV1ContactSyncWebhookSyncId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ContactSync extends ClientSDK {
  async postV1ContactSyncSupabase(
    request?: operations.PostV1ContactSyncSupabaseRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1ContactSyncSupabaseResponse> {
    return unwrapAsync(contactSyncPostV1ContactSyncSupabase(
      this,
      request,
      options,
    ));
  }

  async postV1ContactSyncWebhookSyncId(
    request: operations.PostV1ContactSyncWebhookSyncIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ContactSyncWebhookSyncIdResponse> {
    return unwrapAsync(contactSyncPostV1ContactSyncWebhookSyncId(
      this,
      request,
      options,
    ));
  }

  async getV1ContactSync(
    options?: RequestOptions,
  ): Promise<operations.GetV1ContactSyncResponse> {
    return unwrapAsync(contactSyncGetV1ContactSync(
      this,
      options,
    ));
  }

  async deleteV1ContactSyncId(
    request: operations.DeleteV1ContactSyncIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1ContactSyncIdResponse> {
    return unwrapAsync(contactSyncDeleteV1ContactSyncId(
      this,
      request,
      options,
    ));
  }
}
