/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsAdd } from "../funcs/domainsAdd.js";
import { domainsDelete } from "../funcs/domainsDelete.js";
import { domainsGetDnsStatus } from "../funcs/domainsGetDnsStatus.js";
import { domainsList } from "../funcs/domainsList.js";
import { domainsUpdate } from "../funcs/domainsUpdate.js";
import { domainsVerify } from "../funcs/domainsVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Domains extends ClientSDK {
  /**
   * Add domain
   *
   * @remarks
   * Add a new domain with BYODKIM
   */
  async add(
    request?: models.AddDomainRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Domain> {
    return unwrapAsync(domainsAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * List domains
   *
   * @remarks
   * Get all domains for your organization
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.Domain>> {
    return unwrapAsync(domainsList(
      this,
      options,
    ));
  }

  /**
   * Verify domain
   *
   * @remarks
   * Check domain verification status with SES
   */
  async verify(
    request: operations.VerifyDomainRequest,
    options?: RequestOptions,
  ): Promise<models.DomainVerificationStatus> {
    return unwrapAsync(domainsVerify(
      this,
      request,
      options,
    ));
  }

  /**
   * Get DNS status
   *
   * @remarks
   * Check DNS records verification status
   */
  async getDnsStatus(
    request: operations.GetDomainDnsStatusRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: models.DnsVerificationStatus }> {
    return unwrapAsync(domainsGetDnsStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Update domain
   *
   * @remarks
   * Update domain settings
   */
  async update(
    request: operations.UpdateDomainRequest,
    options?: RequestOptions,
  ): Promise<models.Domain> {
    return unwrapAsync(domainsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete domain
   *
   * @remarks
   * Delete a domain and remove it from SES
   */
  async delete(
    request: operations.DeleteDomainRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(domainsDelete(
      this,
      request,
      options,
    ));
  }
}
