/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailsGet } from "../funcs/emailsGet.js";
import { emailsList } from "../funcs/emailsList.js";
import { emailsSend } from "../funcs/emailsSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Emails extends ClientSDK {
  /**
   * Send an email
   *
   * @remarks
   * Send an email to one or multiple recipients
   */
  async send(
    request?: models.SendEmailRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.SendEmailResponse> {
    return unwrapAsync(emailsSend(
      this,
      request,
      options,
    ));
  }

  /**
   * Get email by ID
   *
   * @remarks
   * Retrieve details of a specific email
   */
  async get(
    request: operations.GetEmailRequest,
    options?: RequestOptions,
  ): Promise<models.Email> {
    return unwrapAsync(emailsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * List emails
   *
   * @remarks
   * Get a paginated list of sent emails
   */
  async list(
    request?: operations.ListEmailsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListEmailsResponse> {
    return unwrapAsync(emailsList(
      this,
      request,
      options,
    ));
  }
}
