/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsDeleteV1IntegrationsId } from "../funcs/integrationsDeleteV1IntegrationsId.js";
import { integrationsGetV1IntegrationsConnections } from "../funcs/integrationsGetV1IntegrationsConnections.js";
import { integrationsGetV1IntegrationsSupabaseAuthorize } from "../funcs/integrationsGetV1IntegrationsSupabaseAuthorize.js";
import { integrationsGetV1IntegrationsSupabaseCallback } from "../funcs/integrationsGetV1IntegrationsSupabaseCallback.js";
import { integrationsGetV1IntegrationsVercelAuthorize } from "../funcs/integrationsGetV1IntegrationsVercelAuthorize.js";
import { integrationsGetV1IntegrationsVercelCallback } from "../funcs/integrationsGetV1IntegrationsVercelCallback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Integrations extends ClientSDK {
  async getV1IntegrationsConnections(
    options?: RequestOptions,
  ): Promise<operations.GetV1IntegrationsConnectionsResponse> {
    return unwrapAsync(integrationsGetV1IntegrationsConnections(
      this,
      options,
    ));
  }

  async getV1IntegrationsSupabaseAuthorize(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(integrationsGetV1IntegrationsSupabaseAuthorize(
      this,
      options,
    ));
  }

  async getV1IntegrationsSupabaseCallback(
    request: operations.GetV1IntegrationsSupabaseCallbackRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(integrationsGetV1IntegrationsSupabaseCallback(
      this,
      request,
      options,
    ));
  }

  async deleteV1IntegrationsId(
    request: operations.DeleteV1IntegrationsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1IntegrationsIdResponse> {
    return unwrapAsync(integrationsDeleteV1IntegrationsId(
      this,
      request,
      options,
    ));
  }

  async getV1IntegrationsVercelAuthorize(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(integrationsGetV1IntegrationsVercelAuthorize(
      this,
      options,
    ));
  }

  async getV1IntegrationsVercelCallback(
    request: operations.GetV1IntegrationsVercelCallbackRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(integrationsGetV1IntegrationsVercelCallback(
      this,
      request,
      options,
    ));
  }
}
