/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logsList } from "../funcs/logsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Logs extends ClientSDK {
  /**
   * Get email logs
   *
   * @remarks
   * Get email events and logs with optional filtering
   */
  async list(
    request?: operations.ListLogsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.EmailEvent>> {
    return unwrapAsync(logsList(
      this,
      request,
      options,
    ));
  }
}
