/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsGetEmail } from "../funcs/metricsGetEmail.js";
import { metricsGetUsage } from "../funcs/metricsGetUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Metrics extends ClientSDK {
  /**
   * Get usage metrics
   *
   * @remarks
   * Get usage metrics for a specified number of days
   */
  async getUsage(
    request?: operations.GetUsageRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.UsageMetric>> {
    return unwrapAsync(metricsGetUsage(
      this,
      request,
      options,
    ));
  }

  /**
   * Get email metrics
   *
   * @remarks
   * Get aggregated email delivery metrics
   */
  async getEmail(
    options?: RequestOptions,
  ): Promise<models.EmailMetrics> {
    return unwrapAsync(metricsGetEmail(
      this,
      options,
    ));
  }
}
