/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { ApiKeys } from "./apikeys.js";
import { Billing } from "./billing.js";
import { Broadcasts } from "./broadcasts.js";
import { Contacts } from "./contacts.js";
import { ContactSync } from "./contactsync.js";
import { Domains } from "./domains.js";
import { Emails } from "./emails.js";
import { Integrations } from "./integrations.js";
import { Logs } from "./logs.js";
import { Metrics } from "./metrics.js";
import { Segments } from "./segments.js";
import { Settings } from "./settings.js";
import { Smtp } from "./smtp.js";
import { Templates } from "./templates.js";
import { Topics } from "./topics.js";
import { Unsubscribe } from "./unsubscribe.js";
import { Webhooks } from "./webhooks.js";

export class Emailr extends ClientSDK {
  private _emails?: Emails;
  get emails(): Emails {
    return (this._emails ??= new Emails(this._options));
  }

  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _templates?: Templates;
  get templates(): Templates {
    return (this._templates ??= new Templates(this._options));
  }

  private _domains?: Domains;
  get domains(): Domains {
    return (this._domains ??= new Domains(this._options));
  }

  private _apiKeys?: ApiKeys;
  get apiKeys(): ApiKeys {
    return (this._apiKeys ??= new ApiKeys(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  private _broadcasts?: Broadcasts;
  get broadcasts(): Broadcasts {
    return (this._broadcasts ??= new Broadcasts(this._options));
  }

  private _segments?: Segments;
  get segments(): Segments {
    return (this._segments ??= new Segments(this._options));
  }

  private _metrics?: Metrics;
  get metrics(): Metrics {
    return (this._metrics ??= new Metrics(this._options));
  }

  private _logs?: Logs;
  get logs(): Logs {
    return (this._logs ??= new Logs(this._options));
  }

  private _settings?: Settings;
  get settings(): Settings {
    return (this._settings ??= new Settings(this._options));
  }

  private _smtp?: Smtp;
  get smtp(): Smtp {
    return (this._smtp ??= new Smtp(this._options));
  }

  private _billing?: Billing;
  get billing(): Billing {
    return (this._billing ??= new Billing(this._options));
  }

  private _topics?: Topics;
  get topics(): Topics {
    return (this._topics ??= new Topics(this._options));
  }

  private _unsubscribe?: Unsubscribe;
  get unsubscribe(): Unsubscribe {
    return (this._unsubscribe ??= new Unsubscribe(this._options));
  }

  private _integrations?: Integrations;
  get integrations(): Integrations {
    return (this._integrations ??= new Integrations(this._options));
  }

  private _contactSync?: ContactSync;
  get contactSync(): ContactSync {
    return (this._contactSync ??= new ContactSync(this._options));
  }
}
