/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { segmentsAddContact } from "../funcs/segmentsAddContact.js";
import { segmentsCreate } from "../funcs/segmentsCreate.js";
import { segmentsList } from "../funcs/segmentsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Segments extends ClientSDK {
  /**
   * Create segment
   *
   * @remarks
   * Create a new contact segment
   */
  async create(
    request?: models.CreateSegmentRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Segment> {
    return unwrapAsync(segmentsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List segments
   *
   * @remarks
   * Get all segments for your organization
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.Segment>> {
    return unwrapAsync(segmentsList(
      this,
      options,
    ));
  }

  /**
   * Add contact to segment
   *
   * @remarks
   * Add a contact to a segment
   */
  async addContact(
    request: operations.AddContactToSegmentRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(segmentsAddContact(
      this,
      request,
      options,
    ));
  }
}
