/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settingsGetOrganization } from "../funcs/settingsGetOrganization.js";
import { settingsGetTeam } from "../funcs/settingsGetTeam.js";
import { settingsGetUnsubscribe } from "../funcs/settingsGetUnsubscribe.js";
import { settingsUpdateOrganization } from "../funcs/settingsUpdateOrganization.js";
import { settingsUpdateUnsubscribe } from "../funcs/settingsUpdateUnsubscribe.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Settings extends ClientSDK {
  /**
   * Get organization settings
   *
   * @remarks
   * Get your organization's settings
   */
  async getOrganization(
    options?: RequestOptions,
  ): Promise<models.Organization> {
    return unwrapAsync(settingsGetOrganization(
      this,
      options,
    ));
  }

  /**
   * Update organization settings
   *
   * @remarks
   * Update your organization's settings
   */
  async updateOrganization(
    request?: models.UpdateOrganizationRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Organization> {
    return unwrapAsync(settingsUpdateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Get team members
   *
   * @remarks
   * Get all team members in your organization
   */
  async getTeam(
    options?: RequestOptions,
  ): Promise<Array<models.TeamMember>> {
    return unwrapAsync(settingsGetTeam(
      this,
      options,
    ));
  }

  /**
   * Get unsubscribe settings
   *
   * @remarks
   * Get unsubscribe page settings
   */
  async getUnsubscribe(
    options?: RequestOptions,
  ): Promise<models.UnsubscribeSettings> {
    return unwrapAsync(settingsGetUnsubscribe(
      this,
      options,
    ));
  }

  /**
   * Update unsubscribe settings
   *
   * @remarks
   * Update unsubscribe page settings
   */
  async updateUnsubscribe(
    request?: models.UpdateUnsubscribeSettingsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.UnsubscribeSettings> {
    return unwrapAsync(settingsUpdateUnsubscribe(
      this,
      request,
      options,
    ));
  }
}
