/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { smtpGetSmtpCredentials } from "../funcs/smtpGetSmtpCredentials.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Smtp extends ClientSDK {
  /**
   * Get SMTP credentials
   *
   * @remarks
   * Get SMTP server credentials for sending emails. The password is your API key.
   */
  async getSmtpCredentials(
    options?: RequestOptions,
  ): Promise<models.SmtpCredentials> {
    return unwrapAsync(smtpGetSmtpCredentials(
      this,
      options,
    ));
  }
}
