/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesCreate } from "../funcs/templatesCreate.js";
import { templatesDelete } from "../funcs/templatesDelete.js";
import { templatesGet } from "../funcs/templatesGet.js";
import { templatesList } from "../funcs/templatesList.js";
import { templatesUpdate } from "../funcs/templatesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Templates extends ClientSDK {
  /**
   * Create a template
   *
   * @remarks
   * Create a new email template
   */
  async create(
    request?: models.CreateTemplateRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Template> {
    return unwrapAsync(templatesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List templates
   *
   * @remarks
   * Get all email templates for your organization
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.Template>> {
    return unwrapAsync(templatesList(
      this,
      options,
    ));
  }

  /**
   * Get template
   *
   * @remarks
   * Get a specific template by ID
   */
  async get(
    request: operations.GetTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.Template> {
    return unwrapAsync(templatesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update template
   *
   * @remarks
   * Update an existing template
   */
  async update(
    request: operations.UpdateTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.Template> {
    return unwrapAsync(templatesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete template
   *
   * @remarks
   * Delete a template
   */
  async delete(
    request: operations.DeleteTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(templatesDelete(
      this,
      request,
      options,
    ));
  }
}
