/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { topicsDeleteV1TopicsId } from "../funcs/topicsDeleteV1TopicsId.js";
import { topicsGetV1Topics } from "../funcs/topicsGetV1Topics.js";
import { topicsPostV1Topics } from "../funcs/topicsPostV1Topics.js";
import { topicsPutV1TopicsId } from "../funcs/topicsPutV1TopicsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Topics extends ClientSDK {
  async getV1Topics(
    options?: RequestOptions,
  ): Promise<operations.GetV1TopicsResponse> {
    return unwrapAsync(topicsGetV1Topics(
      this,
      options,
    ));
  }

  async postV1Topics(
    request?: operations.PostV1TopicsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1TopicsResponse> {
    return unwrapAsync(topicsPostV1Topics(
      this,
      request,
      options,
    ));
  }

  async putV1TopicsId(
    request: operations.PutV1TopicsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PutV1TopicsIdResponse> {
    return unwrapAsync(topicsPutV1TopicsId(
      this,
      request,
      options,
    ));
  }

  async deleteV1TopicsId(
    request: operations.DeleteV1TopicsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1TopicsIdResponse> {
    return unwrapAsync(topicsDeleteV1TopicsId(
      this,
      request,
      options,
    ));
  }
}
