/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { unsubscribeGetV1UnsubscribeOrganizationId } from "../funcs/unsubscribeGetV1UnsubscribeOrganizationId.js";
import { unsubscribePostV1Unsubscribe } from "../funcs/unsubscribePostV1Unsubscribe.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Unsubscribe extends ClientSDK {
  async getV1UnsubscribeOrganizationId(
    request: operations.GetV1UnsubscribeOrganizationIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1UnsubscribeOrganizationIdResponse> {
    return unwrapAsync(unsubscribeGetV1UnsubscribeOrganizationId(
      this,
      request,
      options,
    ));
  }

  async postV1Unsubscribe(
    request?: operations.PostV1UnsubscribeRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1UnsubscribeResponse> {
    return unwrapAsync(unsubscribePostV1Unsubscribe(
      this,
      request,
      options,
    ));
  }
}
