/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreate } from "../funcs/webhooksCreate.js";
import { webhooksDelete } from "../funcs/webhooksDelete.js";
import { webhooksGetDeliveries } from "../funcs/webhooksGetDeliveries.js";
import { webhooksList } from "../funcs/webhooksList.js";
import { webhooksToggle } from "../funcs/webhooksToggle.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Create webhook
   *
   * @remarks
   * Create a new webhook endpoint for event notifications
   */
  async create(
    request?: models.CreateWebhookRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Webhook> {
    return unwrapAsync(webhooksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List webhooks
   *
   * @remarks
   * Get all webhooks for your organization
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.Webhook>> {
    return unwrapAsync(webhooksList(
      this,
      options,
    ));
  }

  /**
   * Toggle webhook
   *
   * @remarks
   * Enable or disable a webhook
   */
  async toggle(
    request: operations.ToggleWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.WebhookToggleResponse> {
    return unwrapAsync(webhooksToggle(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete webhook
   *
   * @remarks
   * Delete a webhook and its delivery history
   */
  async delete(
    request: operations.DeleteWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.Success> {
    return unwrapAsync(webhooksDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get webhook deliveries
   *
   * @remarks
   * Get recent delivery attempts for a webhook
   */
  async getDeliveries(
    request: operations.GetWebhookDeliveriesRequest,
    options?: RequestOptions,
  ): Promise<Array<models.WebhookDelivery>> {
    return unwrapAsync(webhooksGetDeliveries(
      this,
      request,
      options,
    ));
  }
}
