workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Emailr API:
        inputs:
            - location: https://api.emailr.dev/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/hormo/emailr/emailr-api
targets:
    emailr:
        target: typescript
        source: Emailr API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hormo/emailr/emailr-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
