/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AddContactToSegmentRequest = {
  id: string;
  contactId: string;
};

/** @internal */
export type AddContactToSegmentRequest$Outbound = {
  id: string;
  contactId: string;
};

/** @internal */
export const AddContactToSegmentRequest$outboundSchema: z.ZodMiniType<
  AddContactToSegmentRequest$Outbound,
  AddContactToSegmentRequest
> = z.object({
  id: z.string(),
  contactId: z.string(),
});

export function addContactToSegmentRequestToJSON(
  addContactToSegmentRequest: AddContactToSegmentRequest,
): string {
  return JSON.stringify(
    AddContactToSegmentRequest$outboundSchema.parse(addContactToSegmentRequest),
  );
}
