/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV1IntegrationsIdRequest = {
  id: string;
};

/**
 * Connection deleted
 */
export type DeleteV1IntegrationsIdResponse = {
  success: boolean;
};

/** @internal */
export type DeleteV1IntegrationsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1IntegrationsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1IntegrationsIdRequest$Outbound,
  DeleteV1IntegrationsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1IntegrationsIdRequestToJSON(
  deleteV1IntegrationsIdRequest: DeleteV1IntegrationsIdRequest,
): string {
  return JSON.stringify(
    DeleteV1IntegrationsIdRequest$outboundSchema.parse(
      deleteV1IntegrationsIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV1IntegrationsIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1IntegrationsIdResponse,
  unknown
> = z.object({
  success: types.boolean(),
});

export function deleteV1IntegrationsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1IntegrationsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1IntegrationsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1IntegrationsIdResponse' from JSON`,
  );
}
