/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteDomainRequest = {
  id: string;
};

/** @internal */
export type DeleteDomainRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteDomainRequest$outboundSchema: z.ZodMiniType<
  DeleteDomainRequest$Outbound,
  DeleteDomainRequest
> = z.object({
  id: z.string(),
});

export function deleteDomainRequestToJSON(
  deleteDomainRequest: DeleteDomainRequest,
): string {
  return JSON.stringify(
    DeleteDomainRequest$outboundSchema.parse(deleteDomainRequest),
  );
}
