/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteContactRequest = {
  id: string;
};

/** @internal */
export type DeleteContactRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteContactRequest$outboundSchema: z.ZodMiniType<
  DeleteContactRequest$Outbound,
  DeleteContactRequest
> = z.object({
  id: z.string(),
});

export function deleteContactRequestToJSON(
  deleteContactRequest: DeleteContactRequest,
): string {
  return JSON.stringify(
    DeleteContactRequest$outboundSchema.parse(deleteContactRequest),
  );
}
