/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV1ContactSyncIdRequest = {
  id: string;
};

/**
 * Sync deleted
 */
export type DeleteV1ContactSyncIdResponse = {
  success: boolean;
};

/** @internal */
export type DeleteV1ContactSyncIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1ContactSyncIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1ContactSyncIdRequest$Outbound,
  DeleteV1ContactSyncIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1ContactSyncIdRequestToJSON(
  deleteV1ContactSyncIdRequest: DeleteV1ContactSyncIdRequest,
): string {
  return JSON.stringify(
    DeleteV1ContactSyncIdRequest$outboundSchema.parse(
      deleteV1ContactSyncIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV1ContactSyncIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1ContactSyncIdResponse,
  unknown
> = z.object({
  success: types.boolean(),
});

export function deleteV1ContactSyncIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1ContactSyncIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1ContactSyncIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1ContactSyncIdResponse' from JSON`,
  );
}
