/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV1TopicsIdRequest = {
  id: string;
};

/**
 * Topic deleted
 */
export type DeleteV1TopicsIdResponse = {
  success: boolean;
};

/** @internal */
export type DeleteV1TopicsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1TopicsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1TopicsIdRequest$Outbound,
  DeleteV1TopicsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1TopicsIdRequestToJSON(
  deleteV1TopicsIdRequest: DeleteV1TopicsIdRequest,
): string {
  return JSON.stringify(
    DeleteV1TopicsIdRequest$outboundSchema.parse(deleteV1TopicsIdRequest),
  );
}

/** @internal */
export const DeleteV1TopicsIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1TopicsIdResponse,
  unknown
> = z.object({
  success: types.boolean(),
});

export function deleteV1TopicsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1TopicsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1TopicsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1TopicsIdResponse' from JSON`,
  );
}
