/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteWebhookRequest = {
  id: string;
};

/** @internal */
export type DeleteWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteWebhookRequest$outboundSchema: z.ZodMiniType<
  DeleteWebhookRequest$Outbound,
  DeleteWebhookRequest
> = z.object({
  id: z.string(),
});

export function deleteWebhookRequestToJSON(
  deleteWebhookRequest: DeleteWebhookRequest,
): string {
  return JSON.stringify(
    DeleteWebhookRequest$outboundSchema.parse(deleteWebhookRequest),
  );
}
