/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetBroadcastRequest = {
  id: string;
};

/** @internal */
export type GetBroadcastRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetBroadcastRequest$outboundSchema: z.ZodMiniType<
  GetBroadcastRequest$Outbound,
  GetBroadcastRequest
> = z.object({
  id: z.string(),
});

export function getBroadcastRequestToJSON(
  getBroadcastRequest: GetBroadcastRequest,
): string {
  return JSON.stringify(
    GetBroadcastRequest$outboundSchema.parse(getBroadcastRequest),
  );
}
