/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetDomainDnsStatusRequest = {
  id: string;
};

/** @internal */
export type GetDomainDnsStatusRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetDomainDnsStatusRequest$outboundSchema: z.ZodMiniType<
  GetDomainDnsStatusRequest$Outbound,
  GetDomainDnsStatusRequest
> = z.object({
  id: z.string(),
});

export function getDomainDnsStatusRequestToJSON(
  getDomainDnsStatusRequest: GetDomainDnsStatusRequest,
): string {
  return JSON.stringify(
    GetDomainDnsStatusRequest$outboundSchema.parse(getDomainDnsStatusRequest),
  );
}
