/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEmailRequest = {
  id: string;
};

/** @internal */
export type GetEmailRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEmailRequest$outboundSchema: z.ZodMiniType<
  GetEmailRequest$Outbound,
  GetEmailRequest
> = z.object({
  id: z.string(),
});

export function getEmailRequestToJSON(
  getEmailRequest: GetEmailRequest,
): string {
  return JSON.stringify(GetEmailRequest$outboundSchema.parse(getEmailRequest));
}
