/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetTemplateRequest = {
  id: string;
};

/** @internal */
export type GetTemplateRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTemplateRequest$outboundSchema: z.ZodMiniType<
  GetTemplateRequest$Outbound,
  GetTemplateRequest
> = z.object({
  id: z.string(),
});

export function getTemplateRequestToJSON(
  getTemplateRequest: GetTemplateRequest,
): string {
  return JSON.stringify(
    GetTemplateRequest$outboundSchema.parse(getTemplateRequest),
  );
}
