/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetUsageRequest = {
  days?: string | undefined;
};

/** @internal */
export type GetUsageRequest$Outbound = {
  days?: string | undefined;
};

/** @internal */
export const GetUsageRequest$outboundSchema: z.ZodMiniType<
  GetUsageRequest$Outbound,
  GetUsageRequest
> = z.object({
  days: z.optional(z.string()),
});

export function getUsageRequestToJSON(
  getUsageRequest: GetUsageRequest,
): string {
  return JSON.stringify(GetUsageRequest$outboundSchema.parse(getUsageRequest));
}
