/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1TopicsTopic = {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * List of topics
 */
export type GetV1TopicsResponse = {
  topics: Array<GetV1TopicsTopic>;
};

/** @internal */
export const GetV1TopicsTopic$inboundSchema: z.ZodMiniType<
  GetV1TopicsTopic,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    created_at: types.string(),
    updated_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function getV1TopicsTopicFromJSON(
  jsonString: string,
): SafeParseResult<GetV1TopicsTopic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1TopicsTopic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1TopicsTopic' from JSON`,
  );
}

/** @internal */
export const GetV1TopicsResponse$inboundSchema: z.ZodMiniType<
  GetV1TopicsResponse,
  unknown
> = z.object({
  topics: z.array(z.lazy(() => GetV1TopicsTopic$inboundSchema)),
});

export function getV1TopicsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1TopicsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1TopicsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1TopicsResponse' from JSON`,
  );
}
