/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Current usage
 */
export type GetV1BillingUsageResponse = {
  organizationId: string;
  month: string;
  transactionalEmails: number;
  marketingEmails: number;
  transactionalLimit: number | null;
  marketingLimit: number | null;
  transactionalPercentUsed: number;
  marketingPercentUsed: number;
};

/** @internal */
export const GetV1BillingUsageResponse$inboundSchema: z.ZodMiniType<
  GetV1BillingUsageResponse,
  unknown
> = z.object({
  organizationId: types.string(),
  month: types.string(),
  transactionalEmails: types.number(),
  marketingEmails: types.number(),
  transactionalLimit: types.nullable(types.number()),
  marketingLimit: types.nullable(types.number()),
  transactionalPercentUsed: types.number(),
  marketingPercentUsed: types.number(),
});

export function getV1BillingUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BillingUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BillingUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BillingUsageResponse' from JSON`,
  );
}
