/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Provider = {
  Supabase: "supabase",
  Vercel: "vercel",
} as const;
export type Provider = OpenEnum<typeof Provider>;

export type Connection = {
  id: string;
  provider: Provider;
  providerUserId: string;
  providerMetadata?: any | null | undefined;
  createdAt: string;
};

/**
 * List of OAuth connections
 */
export type GetV1IntegrationsConnectionsResponse = {
  connections: Array<Connection>;
};

/** @internal */
export const Provider$inboundSchema: z.ZodMiniType<Provider, unknown> =
  openEnums.inboundSchema(Provider);

/** @internal */
export const Connection$inboundSchema: z.ZodMiniType<Connection, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      provider: Provider$inboundSchema,
      provider_user_id: types.string(),
      provider_metadata: z.optional(z.nullable(z.any())),
      created_at: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "provider_user_id": "providerUserId",
        "provider_metadata": "providerMetadata",
        "created_at": "createdAt",
      });
    }),
  );

export function connectionFromJSON(
  jsonString: string,
): SafeParseResult<Connection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connection' from JSON`,
  );
}

/** @internal */
export const GetV1IntegrationsConnectionsResponse$inboundSchema: z.ZodMiniType<
  GetV1IntegrationsConnectionsResponse,
  unknown
> = z.object({
  connections: z.array(z.lazy(() => Connection$inboundSchema)),
});

export function getV1IntegrationsConnectionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1IntegrationsConnectionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1IntegrationsConnectionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1IntegrationsConnectionsResponse' from JSON`,
  );
}
