/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1UnsubscribeOrganizationIdRequest = {
  organizationId: string;
  email: string;
};

export type GetV1UnsubscribeOrganizationIdTopic = {
  id: string;
  name: string;
  description: string | null;
};

/**
 * Unsubscribe page data
 */
export type GetV1UnsubscribeOrganizationIdResponse = {
  organizationName: string;
  companyName: string | null;
  logoUrl: string | null;
  primaryColor: string | null;
  topics: Array<GetV1UnsubscribeOrganizationIdTopic>;
  contactEmail: string;
  currentUnsubscribes: Array<string>;
};

/** @internal */
export type GetV1UnsubscribeOrganizationIdRequest$Outbound = {
  organizationId: string;
  email: string;
};

/** @internal */
export const GetV1UnsubscribeOrganizationIdRequest$outboundSchema:
  z.ZodMiniType<
    GetV1UnsubscribeOrganizationIdRequest$Outbound,
    GetV1UnsubscribeOrganizationIdRequest
  > = z.object({
    organizationId: z.string(),
    email: z.string(),
  });

export function getV1UnsubscribeOrganizationIdRequestToJSON(
  getV1UnsubscribeOrganizationIdRequest: GetV1UnsubscribeOrganizationIdRequest,
): string {
  return JSON.stringify(
    GetV1UnsubscribeOrganizationIdRequest$outboundSchema.parse(
      getV1UnsubscribeOrganizationIdRequest,
    ),
  );
}

/** @internal */
export const GetV1UnsubscribeOrganizationIdTopic$inboundSchema: z.ZodMiniType<
  GetV1UnsubscribeOrganizationIdTopic,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  description: types.nullable(types.string()),
});

export function getV1UnsubscribeOrganizationIdTopicFromJSON(
  jsonString: string,
): SafeParseResult<GetV1UnsubscribeOrganizationIdTopic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1UnsubscribeOrganizationIdTopic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1UnsubscribeOrganizationIdTopic' from JSON`,
  );
}

/** @internal */
export const GetV1UnsubscribeOrganizationIdResponse$inboundSchema:
  z.ZodMiniType<GetV1UnsubscribeOrganizationIdResponse, unknown> = z.object({
    organizationName: types.string(),
    companyName: types.nullable(types.string()),
    logoUrl: types.nullable(types.string()),
    primaryColor: types.nullable(types.string()),
    topics: z.array(
      z.lazy(() => GetV1UnsubscribeOrganizationIdTopic$inboundSchema),
    ),
    contactEmail: types.string(),
    currentUnsubscribes: z.array(types.string()),
  });

export function getV1UnsubscribeOrganizationIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1UnsubscribeOrganizationIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1UnsubscribeOrganizationIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1UnsubscribeOrganizationIdResponse' from JSON`,
  );
}
