/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1IntegrationsVercelCallbackRequest = {
  code: string;
  state: string;
};

/** @internal */
export type GetV1IntegrationsVercelCallbackRequest$Outbound = {
  code: string;
  state: string;
};

/** @internal */
export const GetV1IntegrationsVercelCallbackRequest$outboundSchema:
  z.ZodMiniType<
    GetV1IntegrationsVercelCallbackRequest$Outbound,
    GetV1IntegrationsVercelCallbackRequest
  > = z.object({
    code: z.string(),
    state: z.string(),
  });

export function getV1IntegrationsVercelCallbackRequestToJSON(
  getV1IntegrationsVercelCallbackRequest:
    GetV1IntegrationsVercelCallbackRequest,
): string {
  return JSON.stringify(
    GetV1IntegrationsVercelCallbackRequest$outboundSchema.parse(
      getV1IntegrationsVercelCallbackRequest,
    ),
  );
}
