/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetV1ContactSyncSourceType = {
  Supabase: "supabase",
  Vercel: "vercel",
  Webhook: "webhook",
} as const;
export type GetV1ContactSyncSourceType = OpenEnum<
  typeof GetV1ContactSyncSourceType
>;

export type Sync = {
  id: string;
  organizationId: string;
  sourceType: GetV1ContactSyncSourceType;
  sourceProjectId: string;
  sourceTable: string;
  fieldMappings?: any | null | undefined;
  syncEnabled: boolean;
  createdAt: string;
};

/**
 * List of contact syncs
 */
export type GetV1ContactSyncResponse = {
  syncs: Array<Sync>;
};

/** @internal */
export const GetV1ContactSyncSourceType$inboundSchema: z.ZodMiniType<
  GetV1ContactSyncSourceType,
  unknown
> = openEnums.inboundSchema(GetV1ContactSyncSourceType);

/** @internal */
export const Sync$inboundSchema: z.ZodMiniType<Sync, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    source_type: GetV1ContactSyncSourceType$inboundSchema,
    source_project_id: types.string(),
    source_table: types.string(),
    field_mappings: z.optional(z.nullable(z.any())),
    sync_enabled: types.boolean(),
    created_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "source_type": "sourceType",
      "source_project_id": "sourceProjectId",
      "source_table": "sourceTable",
      "field_mappings": "fieldMappings",
      "sync_enabled": "syncEnabled",
      "created_at": "createdAt",
    });
  }),
);

export function syncFromJSON(
  jsonString: string,
): SafeParseResult<Sync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sync' from JSON`,
  );
}

/** @internal */
export const GetV1ContactSyncResponse$inboundSchema: z.ZodMiniType<
  GetV1ContactSyncResponse,
  unknown
> = z.object({
  syncs: z.array(z.lazy(() => Sync$inboundSchema)),
});

export function getV1ContactSyncResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ContactSyncResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ContactSyncResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ContactSyncResponse' from JSON`,
  );
}
