/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1IntegrationsSupabaseCallbackRequest = {
  code: string;
  state: string;
};

/** @internal */
export type GetV1IntegrationsSupabaseCallbackRequest$Outbound = {
  code: string;
  state: string;
};

/** @internal */
export const GetV1IntegrationsSupabaseCallbackRequest$outboundSchema:
  z.ZodMiniType<
    GetV1IntegrationsSupabaseCallbackRequest$Outbound,
    GetV1IntegrationsSupabaseCallbackRequest
  > = z.object({
    code: z.string(),
    state: z.string(),
  });

export function getV1IntegrationsSupabaseCallbackRequestToJSON(
  getV1IntegrationsSupabaseCallbackRequest:
    GetV1IntegrationsSupabaseCallbackRequest,
): string {
  return JSON.stringify(
    GetV1IntegrationsSupabaseCallbackRequest$outboundSchema.parse(
      getV1IntegrationsSupabaseCallbackRequest,
    ),
  );
}
