/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWebhookDeliveriesRequest = {
  id: string;
};

/** @internal */
export type GetWebhookDeliveriesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWebhookDeliveriesRequest$outboundSchema: z.ZodMiniType<
  GetWebhookDeliveriesRequest$Outbound,
  GetWebhookDeliveriesRequest
> = z.object({
  id: z.string(),
});

export function getWebhookDeliveriesRequestToJSON(
  getWebhookDeliveriesRequest: GetWebhookDeliveriesRequest,
): string {
  return JSON.stringify(
    GetWebhookDeliveriesRequest$outboundSchema.parse(
      getWebhookDeliveriesRequest,
    ),
  );
}
