/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListEmailsRequest = {
  page?: string | undefined;
  limit?: string | undefined;
};

export type Pagination = {
  page: number;
  limit: number;
  total: number;
  pages: number;
};

/**
 * List of emails with pagination
 */
export type ListEmailsResponse = {
  data: Array<models.Email>;
  pagination: Pagination;
};

/** @internal */
export type ListEmailsRequest$Outbound = {
  page: string;
  limit: string;
};

/** @internal */
export const ListEmailsRequest$outboundSchema: z.ZodMiniType<
  ListEmailsRequest$Outbound,
  ListEmailsRequest
> = z.object({
  page: z._default(z.string(), "1"),
  limit: z._default(z.string(), "50"),
});

export function listEmailsRequestToJSON(
  listEmailsRequest: ListEmailsRequest,
): string {
  return JSON.stringify(
    ListEmailsRequest$outboundSchema.parse(listEmailsRequest),
  );
}

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    page: types.number(),
    limit: types.number(),
    total: types.number(),
    pages: types.number(),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const ListEmailsResponse$inboundSchema: z.ZodMiniType<
  ListEmailsResponse,
  unknown
> = z.object({
  data: z.array(models.Email$inboundSchema),
  pagination: z.lazy(() => Pagination$inboundSchema),
});

export function listEmailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEmailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEmailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEmailsResponse' from JSON`,
  );
}
