/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListContactsRequest = {
  limit?: string | undefined;
  offset?: string | undefined;
  subscribed?: string | undefined;
};

/** @internal */
export type ListContactsRequest$Outbound = {
  limit?: string | undefined;
  offset?: string | undefined;
  subscribed?: string | undefined;
};

/** @internal */
export const ListContactsRequest$outboundSchema: z.ZodMiniType<
  ListContactsRequest$Outbound,
  ListContactsRequest
> = z.object({
  limit: z.optional(z.string()),
  offset: z.optional(z.string()),
  subscribed: z.optional(z.string()),
});

export function listContactsRequestToJSON(
  listContactsRequest: ListContactsRequest,
): string {
  return JSON.stringify(
    ListContactsRequest$outboundSchema.parse(listContactsRequest),
  );
}
