/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListLogsRequest = {
  emailId?: string | undefined;
  eventType?: string | undefined;
};

/** @internal */
export type ListLogsRequest$Outbound = {
  email_id?: string | undefined;
  event_type?: string | undefined;
};

/** @internal */
export const ListLogsRequest$outboundSchema: z.ZodMiniType<
  ListLogsRequest$Outbound,
  ListLogsRequest
> = z.pipe(
  z.object({
    emailId: z.optional(z.string()),
    eventType: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      emailId: "email_id",
      eventType: "event_type",
    });
  }),
);

export function listLogsRequestToJSON(
  listLogsRequest: ListLogsRequest,
): string {
  return JSON.stringify(ListLogsRequest$outboundSchema.parse(listLogsRequest));
}
