/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1UnsubscribeRequest = {
  email: string;
  organizationId: string;
  topicIds?: Array<string> | undefined;
  unsubscribeAll?: boolean | undefined;
  reason?: string | undefined;
};

/**
 * Unsubscribe processed
 */
export type PostV1UnsubscribeResponse = {
  success: boolean;
  message: string;
};

/** @internal */
export type PostV1UnsubscribeRequest$Outbound = {
  email: string;
  organizationId: string;
  topicIds?: Array<string> | undefined;
  unsubscribeAll?: boolean | undefined;
  reason?: string | undefined;
};

/** @internal */
export const PostV1UnsubscribeRequest$outboundSchema: z.ZodMiniType<
  PostV1UnsubscribeRequest$Outbound,
  PostV1UnsubscribeRequest
> = z.object({
  email: z.string(),
  organizationId: z.string(),
  topicIds: z.optional(z.array(z.string())),
  unsubscribeAll: z.optional(z.boolean()),
  reason: z.optional(z.string()),
});

export function postV1UnsubscribeRequestToJSON(
  postV1UnsubscribeRequest: PostV1UnsubscribeRequest,
): string {
  return JSON.stringify(
    PostV1UnsubscribeRequest$outboundSchema.parse(postV1UnsubscribeRequest),
  );
}

/** @internal */
export const PostV1UnsubscribeResponse$inboundSchema: z.ZodMiniType<
  PostV1UnsubscribeResponse,
  unknown
> = z.object({
  success: types.boolean(),
  message: types.string(),
});

export function postV1UnsubscribeResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1UnsubscribeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1UnsubscribeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1UnsubscribeResponse' from JSON`,
  );
}
