/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Portal session created
 */
export type PostV1BillingPortalResponse = {
  url: string;
};

/** @internal */
export const PostV1BillingPortalResponse$inboundSchema: z.ZodMiniType<
  PostV1BillingPortalResponse,
  unknown
> = z.object({
  url: types.string(),
});

export function postV1BillingPortalResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1BillingPortalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1BillingPortalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1BillingPortalResponse' from JSON`,
  );
}
