/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Webhook processed
 */
export type PostV1BillingWebhooksResponse = {
  received: boolean;
};

/** @internal */
export const PostV1BillingWebhooksResponse$inboundSchema: z.ZodMiniType<
  PostV1BillingWebhooksResponse,
  unknown
> = z.object({
  received: types.boolean(),
});

export function postV1BillingWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1BillingWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1BillingWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1BillingWebhooksResponse' from JSON`,
  );
}
