/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1TopicsRequest = {
  name: string;
  description?: string | undefined;
};

/**
 * Topic created
 */
export type PostV1TopicsResponse = {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export type PostV1TopicsRequest$Outbound = {
  name: string;
  description?: string | undefined;
};

/** @internal */
export const PostV1TopicsRequest$outboundSchema: z.ZodMiniType<
  PostV1TopicsRequest$Outbound,
  PostV1TopicsRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
});

export function postV1TopicsRequestToJSON(
  postV1TopicsRequest: PostV1TopicsRequest,
): string {
  return JSON.stringify(
    PostV1TopicsRequest$outboundSchema.parse(postV1TopicsRequest),
  );
}

/** @internal */
export const PostV1TopicsResponse$inboundSchema: z.ZodMiniType<
  PostV1TopicsResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    created_at: types.string(),
    updated_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function postV1TopicsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1TopicsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1TopicsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1TopicsResponse' from JSON`,
  );
}
