/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PlanType = {
  Transactional: "transactional",
  Marketing: "marketing",
} as const;
export type PlanType = ClosedEnum<typeof PlanType>;

export type PostV1BillingCheckoutRequest = {
  /**
   * Stripe Price ID
   */
  priceId: string;
  planType: PlanType;
};

/**
 * Checkout session created
 */
export type PostV1BillingCheckoutResponse = {
  sessionId: string;
  url: string;
};

/** @internal */
export const PlanType$outboundSchema: z.ZodMiniEnum<typeof PlanType> = z.enum(
  PlanType,
);

/** @internal */
export type PostV1BillingCheckoutRequest$Outbound = {
  priceId: string;
  planType: string;
};

/** @internal */
export const PostV1BillingCheckoutRequest$outboundSchema: z.ZodMiniType<
  PostV1BillingCheckoutRequest$Outbound,
  PostV1BillingCheckoutRequest
> = z.object({
  priceId: z.string(),
  planType: PlanType$outboundSchema,
});

export function postV1BillingCheckoutRequestToJSON(
  postV1BillingCheckoutRequest: PostV1BillingCheckoutRequest,
): string {
  return JSON.stringify(
    PostV1BillingCheckoutRequest$outboundSchema.parse(
      postV1BillingCheckoutRequest,
    ),
  );
}

/** @internal */
export const PostV1BillingCheckoutResponse$inboundSchema: z.ZodMiniType<
  PostV1BillingCheckoutResponse,
  unknown
> = z.object({
  sessionId: types.string(),
  url: types.string(),
});

export function postV1BillingCheckoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1BillingCheckoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1BillingCheckoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1BillingCheckoutResponse' from JSON`,
  );
}
