/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FieldMappings = {
  email: string;
  customId?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  properties?: { [k: string]: string } | undefined;
};

export type PostV1ContactSyncSupabaseRequest = {
  oauthConnectionId: string;
  projectId: string;
  tableName: string;
  fieldMappings: FieldMappings;
};

export const PostV1ContactSyncSupabaseSourceType = {
  Supabase: "supabase",
  Vercel: "vercel",
  Webhook: "webhook",
} as const;
export type PostV1ContactSyncSupabaseSourceType = OpenEnum<
  typeof PostV1ContactSyncSupabaseSourceType
>;

/**
 * Sync created
 */
export type PostV1ContactSyncSupabaseResponse = {
  id: string;
  organizationId: string;
  sourceType: PostV1ContactSyncSupabaseSourceType;
  sourceProjectId: string;
  sourceTable: string;
  fieldMappings?: any | null | undefined;
  syncEnabled: boolean;
  createdAt: string;
};

/** @internal */
export type FieldMappings$Outbound = {
  email: string;
  customId?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  properties?: { [k: string]: string } | undefined;
};

/** @internal */
export const FieldMappings$outboundSchema: z.ZodMiniType<
  FieldMappings$Outbound,
  FieldMappings
> = z.object({
  email: z.string(),
  customId: z.optional(z.string()),
  firstName: z.optional(z.string()),
  lastName: z.optional(z.string()),
  properties: z.optional(z.record(z.string(), z.string())),
});

export function fieldMappingsToJSON(fieldMappings: FieldMappings): string {
  return JSON.stringify(FieldMappings$outboundSchema.parse(fieldMappings));
}

/** @internal */
export type PostV1ContactSyncSupabaseRequest$Outbound = {
  oauthConnectionId: string;
  projectId: string;
  tableName: string;
  fieldMappings: FieldMappings$Outbound;
};

/** @internal */
export const PostV1ContactSyncSupabaseRequest$outboundSchema: z.ZodMiniType<
  PostV1ContactSyncSupabaseRequest$Outbound,
  PostV1ContactSyncSupabaseRequest
> = z.object({
  oauthConnectionId: z.string(),
  projectId: z.string(),
  tableName: z.string(),
  fieldMappings: z.lazy(() => FieldMappings$outboundSchema),
});

export function postV1ContactSyncSupabaseRequestToJSON(
  postV1ContactSyncSupabaseRequest: PostV1ContactSyncSupabaseRequest,
): string {
  return JSON.stringify(
    PostV1ContactSyncSupabaseRequest$outboundSchema.parse(
      postV1ContactSyncSupabaseRequest,
    ),
  );
}

/** @internal */
export const PostV1ContactSyncSupabaseSourceType$inboundSchema: z.ZodMiniType<
  PostV1ContactSyncSupabaseSourceType,
  unknown
> = openEnums.inboundSchema(PostV1ContactSyncSupabaseSourceType);

/** @internal */
export const PostV1ContactSyncSupabaseResponse$inboundSchema: z.ZodMiniType<
  PostV1ContactSyncSupabaseResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    source_type: PostV1ContactSyncSupabaseSourceType$inboundSchema,
    source_project_id: types.string(),
    source_table: types.string(),
    field_mappings: z.optional(z.nullable(z.any())),
    sync_enabled: types.boolean(),
    created_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "source_type": "sourceType",
      "source_project_id": "sourceProjectId",
      "source_table": "sourceTable",
      "field_mappings": "fieldMappings",
      "sync_enabled": "syncEnabled",
      "created_at": "createdAt",
    });
  }),
);

export function postV1ContactSyncSupabaseResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ContactSyncSupabaseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ContactSyncSupabaseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ContactSyncSupabaseResponse' from JSON`,
  );
}
