/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ContactSyncWebhookSyncIdRequest = {
  syncId: string;
  body?: any | null | undefined;
};

/**
 * Webhook processed
 */
export type PostV1ContactSyncWebhookSyncIdResponse = {
  success: boolean;
};

/** @internal */
export type PostV1ContactSyncWebhookSyncIdRequest$Outbound = {
  syncId: string;
  body?: any | null | undefined;
};

/** @internal */
export const PostV1ContactSyncWebhookSyncIdRequest$outboundSchema:
  z.ZodMiniType<
    PostV1ContactSyncWebhookSyncIdRequest$Outbound,
    PostV1ContactSyncWebhookSyncIdRequest
  > = z.object({
    syncId: z.string(),
    body: z.optional(z.nullable(z.any())),
  });

export function postV1ContactSyncWebhookSyncIdRequestToJSON(
  postV1ContactSyncWebhookSyncIdRequest: PostV1ContactSyncWebhookSyncIdRequest,
): string {
  return JSON.stringify(
    PostV1ContactSyncWebhookSyncIdRequest$outboundSchema.parse(
      postV1ContactSyncWebhookSyncIdRequest,
    ),
  );
}

/** @internal */
export const PostV1ContactSyncWebhookSyncIdResponse$inboundSchema:
  z.ZodMiniType<PostV1ContactSyncWebhookSyncIdResponse, unknown> = z.object({
    success: types.boolean(),
  });

export function postV1ContactSyncWebhookSyncIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ContactSyncWebhookSyncIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1ContactSyncWebhookSyncIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ContactSyncWebhookSyncIdResponse' from JSON`,
  );
}
