/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PutV1TopicsIdRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
};

export type PutV1TopicsIdRequest = {
  id: string;
  body?: PutV1TopicsIdRequestBody | undefined;
};

/**
 * Topic updated
 */
export type PutV1TopicsIdResponse = {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export type PutV1TopicsIdRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const PutV1TopicsIdRequestBody$outboundSchema: z.ZodMiniType<
  PutV1TopicsIdRequestBody$Outbound,
  PutV1TopicsIdRequestBody
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
});

export function putV1TopicsIdRequestBodyToJSON(
  putV1TopicsIdRequestBody: PutV1TopicsIdRequestBody,
): string {
  return JSON.stringify(
    PutV1TopicsIdRequestBody$outboundSchema.parse(putV1TopicsIdRequestBody),
  );
}

/** @internal */
export type PutV1TopicsIdRequest$Outbound = {
  id: string;
  body?: PutV1TopicsIdRequestBody$Outbound | undefined;
};

/** @internal */
export const PutV1TopicsIdRequest$outboundSchema: z.ZodMiniType<
  PutV1TopicsIdRequest$Outbound,
  PutV1TopicsIdRequest
> = z.object({
  id: z.string(),
  body: z.optional(z.lazy(() => PutV1TopicsIdRequestBody$outboundSchema)),
});

export function putV1TopicsIdRequestToJSON(
  putV1TopicsIdRequest: PutV1TopicsIdRequest,
): string {
  return JSON.stringify(
    PutV1TopicsIdRequest$outboundSchema.parse(putV1TopicsIdRequest),
  );
}

/** @internal */
export const PutV1TopicsIdResponse$inboundSchema: z.ZodMiniType<
  PutV1TopicsIdResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    created_at: types.string(),
    updated_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function putV1TopicsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutV1TopicsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV1TopicsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV1TopicsIdResponse' from JSON`,
  );
}
