/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RevokeApiKeyRequest = {
  id: string;
};

/** @internal */
export type RevokeApiKeyRequest$Outbound = {
  id: string;
};

/** @internal */
export const RevokeApiKeyRequest$outboundSchema: z.ZodMiniType<
  RevokeApiKeyRequest$Outbound,
  RevokeApiKeyRequest
> = z.object({
  id: z.string(),
});

export function revokeApiKeyRequestToJSON(
  revokeApiKeyRequest: RevokeApiKeyRequest,
): string {
  return JSON.stringify(
    RevokeApiKeyRequest$outboundSchema.parse(revokeApiKeyRequest),
  );
}
