/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SendBroadcastRequest = {
  id: string;
};

/** @internal */
export type SendBroadcastRequest$Outbound = {
  id: string;
};

/** @internal */
export const SendBroadcastRequest$outboundSchema: z.ZodMiniType<
  SendBroadcastRequest$Outbound,
  SendBroadcastRequest
> = z.object({
  id: z.string(),
});

export function sendBroadcastRequestToJSON(
  sendBroadcastRequest: SendBroadcastRequest,
): string {
  return JSON.stringify(
    SendBroadcastRequest$outboundSchema.parse(sendBroadcastRequest),
  );
}
