/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ToggleWebhookRequest = {
  id: string;
};

/** @internal */
export type ToggleWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const ToggleWebhookRequest$outboundSchema: z.ZodMiniType<
  ToggleWebhookRequest$Outbound,
  ToggleWebhookRequest
> = z.object({
  id: z.string(),
});

export function toggleWebhookRequestToJSON(
  toggleWebhookRequest: ToggleWebhookRequest,
): string {
  return JSON.stringify(
    ToggleWebhookRequest$outboundSchema.parse(toggleWebhookRequest),
  );
}
