/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateContactRequest = {
  id: string;
  body?: models.UpdateContactRequest | undefined;
};

/** @internal */
export type UpdateContactRequest$Outbound = {
  id: string;
  body?: models.UpdateContactRequest$Outbound | undefined;
};

/** @internal */
export const UpdateContactRequest$outboundSchema: z.ZodMiniType<
  UpdateContactRequest$Outbound,
  UpdateContactRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.UpdateContactRequest$outboundSchema),
});

export function updateContactRequestToJSON(
  updateContactRequest: UpdateContactRequest,
): string {
  return JSON.stringify(
    UpdateContactRequest$outboundSchema.parse(updateContactRequest),
  );
}
