/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateDomainRequest = {
  id: string;
  body?: models.UpdateDomainRequest | undefined;
};

/** @internal */
export type UpdateDomainRequest$Outbound = {
  id: string;
  body?: models.UpdateDomainRequest$Outbound | undefined;
};

/** @internal */
export const UpdateDomainRequest$outboundSchema: z.ZodMiniType<
  UpdateDomainRequest$Outbound,
  UpdateDomainRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.UpdateDomainRequest$outboundSchema),
});

export function updateDomainRequestToJSON(
  updateDomainRequest: UpdateDomainRequest,
): string {
  return JSON.stringify(
    UpdateDomainRequest$outboundSchema.parse(updateDomainRequest),
  );
}
