/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTemplateRequest = {
  id: string;
  body?: models.CreateTemplateRequest | undefined;
};

/** @internal */
export type UpdateTemplateRequest$Outbound = {
  id: string;
  body?: models.CreateTemplateRequest$Outbound | undefined;
};

/** @internal */
export const UpdateTemplateRequest$outboundSchema: z.ZodMiniType<
  UpdateTemplateRequest$Outbound,
  UpdateTemplateRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.CreateTemplateRequest$outboundSchema),
});

export function updateTemplateRequestToJSON(
  updateTemplateRequest: UpdateTemplateRequest,
): string {
  return JSON.stringify(
    UpdateTemplateRequest$outboundSchema.parse(updateTemplateRequest),
  );
}
