/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type VerifyDomainRequest = {
  id: string;
};

/** @internal */
export type VerifyDomainRequest$Outbound = {
  id: string;
};

/** @internal */
export const VerifyDomainRequest$outboundSchema: z.ZodMiniType<
  VerifyDomainRequest$Outbound,
  VerifyDomainRequest
> = z.object({
  id: z.string(),
});

export function verifyDomainRequestToJSON(
  verifyDomainRequest: VerifyDomainRequest,
): string {
  return JSON.stringify(
    VerifyDomainRequest$outboundSchema.parse(verifyDomainRequest),
  );
}
