/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AddDomainRequest = {
  domain: string;
  receivingSubdomain?: string | undefined;
};

/** @internal */
export type AddDomainRequest$Outbound = {
  domain: string;
  receivingSubdomain: string;
};

/** @internal */
export const AddDomainRequest$outboundSchema: z.ZodMiniType<
  AddDomainRequest$Outbound,
  AddDomainRequest
> = z.object({
  domain: z.string(),
  receivingSubdomain: z._default(z.string(), "mail"),
});

export function addDomainRequestToJSON(
  addDomainRequest: AddDomainRequest,
): string {
  return JSON.stringify(
    AddDomainRequest$outboundSchema.parse(addDomainRequest),
  );
}
