/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiKey = {
  id: string;
  organizationId: string;
  name: string;
  /**
   * Only returned when creating a new key
   */
  key?: string | undefined;
  permissions: Array<string> | null;
  lastUsedAt: Date | null;
  createdBy: string | null;
  createdAt: Date;
  revokedAt: Date | null;
};

/** @internal */
export const ApiKey$inboundSchema: z.ZodMiniType<ApiKey, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    key: types.optional(types.string()),
    permissions: types.nullable(z.array(types.string())),
    last_used_at: types.nullable(types.date()),
    created_by: types.nullable(types.string()),
    created_at: types.date(),
    revoked_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "last_used_at": "lastUsedAt",
      "created_by": "createdBy",
      "created_at": "createdAt",
      "revoked_at": "revokedAt",
    });
  }),
);

export function apiKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKey' from JSON`,
  );
}
