/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiKeyListItem = {
  id: string;
  name: string;
  permissions: Array<string> | null;
  lastUsedAt: Date | null;
  createdAt: Date;
};

/** @internal */
export const ApiKeyListItem$inboundSchema: z.ZodMiniType<
  ApiKeyListItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    permissions: types.nullable(z.array(types.string())),
    last_used_at: types.nullable(types.date()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_used_at": "lastUsedAt",
      "created_at": "createdAt",
    });
  }),
);

export function apiKeyListItemFromJSON(
  jsonString: string,
): SafeParseResult<ApiKeyListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKeyListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKeyListItem' from JSON`,
  );
}
