/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type Attachment = {
  filename: string;
  /**
   * Base64 encoded file content
   */
  content: string;
  contentType?: string | undefined;
};

/** @internal */
export type Attachment$Outbound = {
  filename: string;
  content: string;
  contentType?: string | undefined;
};

/** @internal */
export const Attachment$outboundSchema: z.ZodMiniType<
  Attachment$Outbound,
  Attachment
> = z.object({
  filename: z.string(),
  content: z.string(),
  contentType: z.optional(z.string()),
});

export function attachmentToJSON(attachment: Attachment): string {
  return JSON.stringify(Attachment$outboundSchema.parse(attachment));
}
