/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Broadcast = {
  id: string;
  organizationId: string;
  name: string;
  subject: string;
  fromEmail: string;
  templateId: string | null;
  segmentId: string | null;
  status: string;
  totalRecipients: number | null;
  sentCount: number | null;
  deliveredCount: number | null;
  openedCount: number | null;
  clickedCount: number | null;
  bouncedCount: number | null;
  scheduledAt: Date | null;
  startedAt: Date | null;
  completedAt: Date | null;
  createdBy: string | null;
  createdAt: Date;
};

/** @internal */
export const Broadcast$inboundSchema: z.ZodMiniType<Broadcast, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      organization_id: types.string(),
      name: types.string(),
      subject: types.string(),
      from_email: types.string(),
      template_id: types.nullable(types.string()),
      segment_id: types.nullable(types.string()),
      status: types.string(),
      total_recipients: types.nullable(types.number()),
      sent_count: types.nullable(types.number()),
      delivered_count: types.nullable(types.number()),
      opened_count: types.nullable(types.number()),
      clicked_count: types.nullable(types.number()),
      bounced_count: types.nullable(types.number()),
      scheduled_at: types.nullable(types.date()),
      started_at: types.nullable(types.date()),
      completed_at: types.nullable(types.date()),
      created_by: types.nullable(types.string()),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "organization_id": "organizationId",
        "from_email": "fromEmail",
        "template_id": "templateId",
        "segment_id": "segmentId",
        "total_recipients": "totalRecipients",
        "sent_count": "sentCount",
        "delivered_count": "deliveredCount",
        "opened_count": "openedCount",
        "clicked_count": "clickedCount",
        "bounced_count": "bouncedCount",
        "scheduled_at": "scheduledAt",
        "started_at": "startedAt",
        "completed_at": "completedAt",
        "created_by": "createdBy",
        "created_at": "createdAt",
      });
    }),
  );

export function broadcastFromJSON(
  jsonString: string,
): SafeParseResult<Broadcast, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Broadcast$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Broadcast' from JSON`,
  );
}
