/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BulkCreateContactsResponse = {
  imported: number;
  total: number;
};

/** @internal */
export const BulkCreateContactsResponse$inboundSchema: z.ZodMiniType<
  BulkCreateContactsResponse,
  unknown
> = z.object({
  imported: types.number(),
  total: types.number(),
});

export function bulkCreateContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkCreateContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkCreateContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkCreateContactsResponse' from JSON`,
  );
}
