/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  CreateContactRequest,
  CreateContactRequest$Outbound,
  CreateContactRequest$outboundSchema,
} from "./createcontactrequest.js";

export type BulkCreateContactsRequest = {
  contacts: Array<CreateContactRequest>;
};

/** @internal */
export type BulkCreateContactsRequest$Outbound = {
  contacts: Array<CreateContactRequest$Outbound>;
};

/** @internal */
export const BulkCreateContactsRequest$outboundSchema: z.ZodMiniType<
  BulkCreateContactsRequest$Outbound,
  BulkCreateContactsRequest
> = z.object({
  contacts: z.array(CreateContactRequest$outboundSchema),
});

export function bulkCreateContactsRequestToJSON(
  bulkCreateContactsRequest: BulkCreateContactsRequest,
): string {
  return JSON.stringify(
    BulkCreateContactsRequest$outboundSchema.parse(bulkCreateContactsRequest),
  );
}
