/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Contact = {
  id: string;
  organizationId: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  metadata: { [k: string]: any | null } | null;
  subscribed: boolean;
  unsubscribedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Contact$inboundSchema: z.ZodMiniType<Contact, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    email: types.string(),
    first_name: types.nullable(types.string()),
    last_name: types.nullable(types.string()),
    metadata: types.nullable(z.record(z.string(), types.nullable(z.any()))),
    subscribed: types.boolean(),
    unsubscribed_at: types.nullable(types.date()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "first_name": "firstName",
      "last_name": "lastName",
      "unsubscribed_at": "unsubscribedAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function contactFromJSON(
  jsonString: string,
): SafeParseResult<Contact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Contact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Contact' from JSON`,
  );
}
