/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Contact, Contact$inboundSchema } from "./contact.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ContactListResponse = {
  contacts: Array<Contact>;
  total: number;
  limit: number;
  offset: number;
};

/** @internal */
export const ContactListResponse$inboundSchema: z.ZodMiniType<
  ContactListResponse,
  unknown
> = z.object({
  contacts: z.array(Contact$inboundSchema),
  total: types.number(),
  limit: types.number(),
  offset: types.number(),
});

export function contactListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContactListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactListResponse' from JSON`,
  );
}
