/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateTemplateRequest = {
  name: string;
  subject: string;
  htmlContent?: string | undefined;
  textContent?: string | undefined;
  variables?: Array<string> | undefined;
  /**
   * Default from email address. Must match a verified domain.
   */
  fromEmail?: string | undefined;
  /**
   * Reply-To email address for template-based emails.
   */
  replyTo?: string | undefined;
  /**
   * Preview text (preheader) shown in email clients.
   */
  previewText?: string | undefined;
};

/** @internal */
export type CreateTemplateRequest$Outbound = {
  name: string;
  subject: string;
  html_content?: string | undefined;
  text_content?: string | undefined;
  variables?: Array<string> | undefined;
  from_email?: string | undefined;
  reply_to?: string | undefined;
  preview_text?: string | undefined;
};

/** @internal */
export const CreateTemplateRequest$outboundSchema: z.ZodMiniType<
  CreateTemplateRequest$Outbound,
  CreateTemplateRequest
> = z.pipe(
  z.object({
    name: z.string(),
    subject: z.string(),
    htmlContent: z.optional(z.string()),
    textContent: z.optional(z.string()),
    variables: z.optional(z.array(z.string())),
    fromEmail: z.optional(z.string()),
    replyTo: z.optional(z.string()),
    previewText: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      htmlContent: "html_content",
      textContent: "text_content",
      fromEmail: "from_email",
      replyTo: "reply_to",
      previewText: "preview_text",
    });
  }),
);

export function createTemplateRequestToJSON(
  createTemplateRequest: CreateTemplateRequest,
): string {
  return JSON.stringify(
    CreateTemplateRequest$outboundSchema.parse(createTemplateRequest),
  );
}
