/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateWebhookRequest = {
  name: string;
  url: string;
  events: Array<string>;
};

/** @internal */
export type CreateWebhookRequest$Outbound = {
  name: string;
  url: string;
  events: Array<string>;
};

/** @internal */
export const CreateWebhookRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookRequest$Outbound,
  CreateWebhookRequest
> = z.object({
  name: z.string(),
  url: z.string(),
  events: z.array(z.string()),
});

export function createWebhookRequestToJSON(
  createWebhookRequest: CreateWebhookRequest,
): string {
  return JSON.stringify(
    CreateWebhookRequest$outboundSchema.parse(createWebhookRequest),
  );
}
