/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateSegmentRequest = {
  name: string;
  description?: string | undefined;
  conditions: { [k: string]: any | null };
};

/** @internal */
export type CreateSegmentRequest$Outbound = {
  name: string;
  description?: string | undefined;
  conditions: { [k: string]: any | null };
};

/** @internal */
export const CreateSegmentRequest$outboundSchema: z.ZodMiniType<
  CreateSegmentRequest$Outbound,
  CreateSegmentRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  conditions: z.record(z.string(), z.nullable(z.any())),
});

export function createSegmentRequestToJSON(
  createSegmentRequest: CreateSegmentRequest,
): string {
  return JSON.stringify(
    CreateSegmentRequest$outboundSchema.parse(createSegmentRequest),
  );
}
