/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateTemplateRequest = {
  name: string;
  subject: string;
  htmlContent?: string | undefined;
  textContent?: string | undefined;
  variables?: Array<string> | undefined;
};

/** @internal */
export type CreateTemplateRequest$Outbound = {
  name: string;
  subject: string;
  html_content?: string | undefined;
  text_content?: string | undefined;
  variables?: Array<string> | undefined;
};

/** @internal */
export const CreateTemplateRequest$outboundSchema: z.ZodMiniType<
  CreateTemplateRequest$Outbound,
  CreateTemplateRequest
> = z.pipe(
  z.object({
    name: z.string(),
    subject: z.string(),
    htmlContent: z.optional(z.string()),
    textContent: z.optional(z.string()),
    variables: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      htmlContent: "html_content",
      textContent: "text_content",
    });
  }),
);

export function createTemplateRequestToJSON(
  createTemplateRequest: CreateTemplateRequest,
): string {
  return JSON.stringify(
    CreateTemplateRequest$outboundSchema.parse(createTemplateRequest),
  );
}
