/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateContactRequest = {
  email: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  subscribed?: boolean | undefined;
  metadata?: { [k: string]: any | null } | undefined;
};

/** @internal */
export type CreateContactRequest$Outbound = {
  email: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  subscribed: boolean;
  metadata?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const CreateContactRequest$outboundSchema: z.ZodMiniType<
  CreateContactRequest$Outbound,
  CreateContactRequest
> = z.pipe(
  z.object({
    email: z.string(),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    subscribed: z._default(z.boolean(), true),
    metadata: z.optional(z.record(z.string(), z.nullable(z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      firstName: "first_name",
      lastName: "last_name",
    });
  }),
);

export function createContactRequestToJSON(
  createContactRequest: CreateContactRequest,
): string {
  return JSON.stringify(
    CreateContactRequest$outboundSchema.parse(createContactRequest),
  );
}
