/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateApiKeyRequest = {
  name: string;
  permissions?: Array<string> | undefined;
};

/** @internal */
export type CreateApiKeyRequest$Outbound = {
  name: string;
  permissions?: Array<string> | undefined;
};

/** @internal */
export const CreateApiKeyRequest$outboundSchema: z.ZodMiniType<
  CreateApiKeyRequest$Outbound,
  CreateApiKeyRequest
> = z.object({
  name: z.string(),
  permissions: z.optional(z.array(z.string())),
});

export function createApiKeyRequestToJSON(
  createApiKeyRequest: CreateApiKeyRequest,
): string {
  return JSON.stringify(
    CreateApiKeyRequest$outboundSchema.parse(createApiKeyRequest),
  );
}
