/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateBroadcastRequest = {
  name: string;
  subject: string;
  fromEmail: string;
  templateId?: string | undefined;
  segmentId?: string | undefined;
  htmlContent?: string | undefined;
  textContent?: string | undefined;
  scheduledAt?: Date | undefined;
};

/** @internal */
export type CreateBroadcastRequest$Outbound = {
  name: string;
  subject: string;
  from_email: string;
  template_id?: string | undefined;
  segment_id?: string | undefined;
  html_content?: string | undefined;
  text_content?: string | undefined;
  scheduled_at?: string | undefined;
};

/** @internal */
export const CreateBroadcastRequest$outboundSchema: z.ZodMiniType<
  CreateBroadcastRequest$Outbound,
  CreateBroadcastRequest
> = z.pipe(
  z.object({
    name: z.string(),
    subject: z.string(),
    fromEmail: z.string(),
    templateId: z.optional(z.string()),
    segmentId: z.optional(z.string()),
    htmlContent: z.optional(z.string()),
    textContent: z.optional(z.string()),
    scheduledAt: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      fromEmail: "from_email",
      templateId: "template_id",
      segmentId: "segment_id",
      htmlContent: "html_content",
      textContent: "text_content",
      scheduledAt: "scheduled_at",
    });
  }),
);

export function createBroadcastRequestToJSON(
  createBroadcastRequest: CreateBroadcastRequest,
): string {
  return JSON.stringify(
    CreateBroadcastRequest$outboundSchema.parse(createBroadcastRequest),
  );
}
