/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Type = {
  Txt: "TXT",
  Mx: "MX",
  Cname: "CNAME",
} as const;
export type Type = OpenEnum<typeof Type>;

export type DnsRecord = {
  type: Type;
  name: string;
  value: string;
  priority?: number | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const DnsRecord$inboundSchema: z.ZodMiniType<DnsRecord, unknown> = z
  .object({
    type: Type$inboundSchema,
    name: types.string(),
    value: types.string(),
    priority: types.optional(types.number()),
  });

export function dnsRecordFromJSON(
  jsonString: string,
): SafeParseResult<DnsRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsRecord' from JSON`,
  );
}
