/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DnsVerificationStatus = {
  verified: boolean;
  expected?: string | undefined;
  found?: Array<string> | undefined;
};

/** @internal */
export const DnsVerificationStatus$inboundSchema: z.ZodMiniType<
  DnsVerificationStatus,
  unknown
> = z.object({
  verified: types.boolean(),
  expected: types.optional(types.string()),
  found: types.optional(z.array(types.string())),
});

export function dnsVerificationStatusFromJSON(
  jsonString: string,
): SafeParseResult<DnsVerificationStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsVerificationStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsVerificationStatus' from JSON`,
  );
}
