/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DomainVerificationStatus = {
  verified: boolean;
  status: string;
  dkimStatus?: string | undefined;
};

/** @internal */
export const DomainVerificationStatus$inboundSchema: z.ZodMiniType<
  DomainVerificationStatus,
  unknown
> = z.object({
  verified: types.boolean(),
  status: types.string(),
  dkimStatus: types.optional(types.string()),
});

export function domainVerificationStatusFromJSON(
  jsonString: string,
): SafeParseResult<DomainVerificationStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainVerificationStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainVerificationStatus' from JSON`,
  );
}
