/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { DnsRecord, DnsRecord$inboundSchema } from "./dnsrecord.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DomainDnsRecords = {
  dkim: DnsRecord;
  spf: DnsRecord;
  dmarc: DnsRecord;
  mailFromMx: DnsRecord;
  mailFromSpf: DnsRecord;
  receivingMx: DnsRecord;
};

/** @internal */
export const DomainDnsRecords$inboundSchema: z.ZodMiniType<
  DomainDnsRecords,
  unknown
> = z.object({
  dkim: DnsRecord$inboundSchema,
  spf: DnsRecord$inboundSchema,
  dmarc: DnsRecord$inboundSchema,
  mailFromMx: DnsRecord$inboundSchema,
  mailFromSpf: DnsRecord$inboundSchema,
  receivingMx: DnsRecord$inboundSchema,
});

export function domainDnsRecordsFromJSON(
  jsonString: string,
): SafeParseResult<DomainDnsRecords, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainDnsRecords$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainDnsRecords' from JSON`,
  );
}
