/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DomainDnsRecords,
  DomainDnsRecords$inboundSchema,
} from "./domaindnsrecords.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Domain = {
  id: string;
  organizationId: string;
  domain: string;
  status: string;
  verificationToken: string | null;
  dkimVerified: boolean;
  spfVerified: boolean;
  dmarcVerified: boolean;
  cloudflareZoneId: string | null;
  sesIdentityArn: string | null;
  createdAt: Date;
  verifiedAt: Date | null;
  dkimTokens: Array<string> | null;
  dnsRecords: DomainDnsRecords | null;
  dkimSelector: string | null;
  mailFromSubdomain: string | null;
  mailFromVerified: boolean | null;
  receivingEnabled: boolean | null;
  receivingSubdomain: string | null;
};

/** @internal */
export const Domain$inboundSchema: z.ZodMiniType<Domain, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    domain: types.string(),
    status: types.string(),
    verification_token: types.nullable(types.string()),
    dkim_verified: types.boolean(),
    spf_verified: types.boolean(),
    dmarc_verified: types.boolean(),
    cloudflare_zone_id: types.nullable(types.string()),
    ses_identity_arn: types.nullable(types.string()),
    created_at: types.date(),
    verified_at: types.nullable(types.date()),
    dkim_tokens: types.nullable(z.array(types.string())),
    dns_records: types.nullable(DomainDnsRecords$inboundSchema),
    dkim_selector: types.nullable(types.string()),
    mail_from_subdomain: types.nullable(types.string()),
    mail_from_verified: types.nullable(types.boolean()),
    receiving_enabled: types.nullable(types.boolean()),
    receiving_subdomain: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "verification_token": "verificationToken",
      "dkim_verified": "dkimVerified",
      "spf_verified": "spfVerified",
      "dmarc_verified": "dmarcVerified",
      "cloudflare_zone_id": "cloudflareZoneId",
      "ses_identity_arn": "sesIdentityArn",
      "created_at": "createdAt",
      "verified_at": "verifiedAt",
      "dkim_tokens": "dkimTokens",
      "dns_records": "dnsRecords",
      "dkim_selector": "dkimSelector",
      "mail_from_subdomain": "mailFromSubdomain",
      "mail_from_verified": "mailFromVerified",
      "receiving_enabled": "receivingEnabled",
      "receiving_subdomain": "receivingSubdomain",
    });
  }),
);

export function domainFromJSON(
  jsonString: string,
): SafeParseResult<Domain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Domain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Domain' from JSON`,
  );
}
