/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Email, Email$inboundSchema } from "./email.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type EmailEvent = {
  id: string;
  emailId: string;
  eventType: string;
  eventData: { [k: string]: any | null } | null;
  ipAddress: string | null;
  userAgent: string | null;
  createdAt: Date;
  emails?: Email | undefined;
};

/** @internal */
export const EmailEvent$inboundSchema: z.ZodMiniType<EmailEvent, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      email_id: types.string(),
      event_type: types.string(),
      event_data: types.nullable(z.record(z.string(), types.nullable(z.any()))),
      ip_address: types.nullable(types.string()),
      user_agent: types.nullable(types.string()),
      created_at: types.date(),
      emails: types.optional(Email$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "email_id": "emailId",
        "event_type": "eventType",
        "event_data": "eventData",
        "ip_address": "ipAddress",
        "user_agent": "userAgent",
        "created_at": "createdAt",
      });
    }),
  );

export function emailEventFromJSON(
  jsonString: string,
): SafeParseResult<EmailEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailEvent' from JSON`,
  );
}
