/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Email = {
  id: string;
  organizationId: string;
  messageId: string;
  fromEmail: string;
  toEmail: string;
  subject: string | null;
  htmlContent: string | null;
  textContent: string | null;
  templateId: string | null;
  status: string;
  sesMessageId: string | null;
  broadcastId: string | null;
  metadata: { [k: string]: any | null } | null;
  sentAt: Date | null;
  deliveredAt: Date | null;
  openedAt: Date | null;
  clickedAt: Date | null;
  bouncedAt: Date | null;
  complainedAt: Date | null;
  createdAt: Date;
  threadId: string | null;
  parentEmailId: string | null;
  attachments: Array<any | null> | null;
  clickedLinks: Array<any | null> | null;
  opens: Array<any | null> | null;
};

/** @internal */
export const Email$inboundSchema: z.ZodMiniType<Email, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    message_id: types.string(),
    from_email: types.string(),
    to_email: types.string(),
    subject: types.nullable(types.string()),
    html_content: types.nullable(types.string()),
    text_content: types.nullable(types.string()),
    template_id: types.nullable(types.string()),
    status: types.string(),
    ses_message_id: types.nullable(types.string()),
    broadcast_id: types.nullable(types.string()),
    metadata: types.nullable(z.record(z.string(), types.nullable(z.any()))),
    sent_at: types.nullable(types.date()),
    delivered_at: types.nullable(types.date()),
    opened_at: types.nullable(types.date()),
    clicked_at: types.nullable(types.date()),
    bounced_at: types.nullable(types.date()),
    complained_at: types.nullable(types.date()),
    created_at: types.date(),
    thread_id: types.nullable(types.string()),
    parent_email_id: types.nullable(types.string()),
    attachments: types.nullable(z.array(types.nullable(z.any()))),
    clicked_links: types.nullable(z.array(types.nullable(z.any()))),
    opens: types.nullable(z.array(types.nullable(z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "message_id": "messageId",
      "from_email": "fromEmail",
      "to_email": "toEmail",
      "html_content": "htmlContent",
      "text_content": "textContent",
      "template_id": "templateId",
      "ses_message_id": "sesMessageId",
      "broadcast_id": "broadcastId",
      "sent_at": "sentAt",
      "delivered_at": "deliveredAt",
      "opened_at": "openedAt",
      "clicked_at": "clickedAt",
      "bounced_at": "bouncedAt",
      "complained_at": "complainedAt",
      "created_at": "createdAt",
      "thread_id": "threadId",
      "parent_email_id": "parentEmailId",
      "clicked_links": "clickedLinks",
    });
  }),
);

export function emailFromJSON(
  jsonString: string,
): SafeParseResult<Email, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Email$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Email' from JSON`,
  );
}
