/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type EmailMetrics = {
  total: number;
  sent: number;
  delivered: number;
  bounced: number;
  complained: number;
};

/** @internal */
export const EmailMetrics$inboundSchema: z.ZodMiniType<EmailMetrics, unknown> =
  z.object({
    total: types.number(),
    sent: types.number(),
    delivered: types.number(),
    bounced: types.number(),
    complained: types.number(),
  });

export function emailMetricsFromJSON(
  jsonString: string,
): SafeParseResult<EmailMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailMetrics' from JSON`,
  );
}
