/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Organization = {
  id: string;
  name: string;
  slug: string;
  plan: string | null;
  billingEmail: string | null;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  usageLimit: number | null;
  createdAt: Date;
  updatedAt: Date;
  sesConfigurationSet: string | null;
  sesTenantName: string | null;
  sesTenantId: string | null;
};

/** @internal */
export const Organization$inboundSchema: z.ZodMiniType<Organization, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      slug: types.string(),
      plan: types.nullable(types.string()),
      billing_email: types.nullable(types.string()),
      stripe_customer_id: types.nullable(types.string()),
      stripe_subscription_id: types.nullable(types.string()),
      usage_limit: types.nullable(types.number()),
      created_at: types.date(),
      updated_at: types.date(),
      ses_configuration_set: types.nullable(types.string()),
      ses_tenant_name: types.nullable(types.string()),
      ses_tenant_id: types.nullable(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "billing_email": "billingEmail",
        "stripe_customer_id": "stripeCustomerId",
        "stripe_subscription_id": "stripeSubscriptionId",
        "usage_limit": "usageLimit",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
        "ses_configuration_set": "sesConfigurationSet",
        "ses_tenant_name": "sesTenantName",
        "ses_tenant_id": "sesTenantId",
      });
    }),
  );

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
