/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ReplyTo = {
  inReplyTo?: string | undefined;
  threadId?: string | undefined;
  parentEmailId?: string | undefined;
};

/** @internal */
export type ReplyTo$Outbound = {
  in_reply_to?: string | undefined;
  thread_id?: string | undefined;
  parent_email_id?: string | undefined;
};

/** @internal */
export const ReplyTo$outboundSchema: z.ZodMiniType<ReplyTo$Outbound, ReplyTo> =
  z.pipe(
    z.object({
      inReplyTo: z.optional(z.string()),
      threadId: z.optional(z.string()),
      parentEmailId: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        inReplyTo: "in_reply_to",
        threadId: "thread_id",
        parentEmailId: "parent_email_id",
      });
    }),
  );

export function replyToToJSON(replyTo: ReplyTo): string {
  return JSON.stringify(ReplyTo$outboundSchema.parse(replyTo));
}
