/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  Attachment,
  Attachment$Outbound,
  Attachment$outboundSchema,
} from "./attachment.js";
import {
  ReplyTo,
  ReplyTo$Outbound,
  ReplyTo$outboundSchema,
} from "./replyto.js";

export type To = string | Array<string>;

export type SendEmailRequest = {
  from: string;
  to: string | Array<string>;
  subject: string;
  html?: string | undefined;
  text?: string | undefined;
  templateId?: string | undefined;
  templateData?: { [k: string]: any | null } | undefined;
  tags?: { [k: string]: string } | undefined;
  attachments?: Array<Attachment> | undefined;
  replyTo?: ReplyTo | undefined;
};

/** @internal */
export type To$Outbound = string | Array<string>;

/** @internal */
export const To$outboundSchema: z.ZodMiniType<To$Outbound, To> = smartUnion([
  z.string(),
  z.array(z.string()),
]);

export function toToJSON(to: To): string {
  return JSON.stringify(To$outboundSchema.parse(to));
}

/** @internal */
export type SendEmailRequest$Outbound = {
  from: string;
  to: string | Array<string>;
  subject: string;
  html?: string | undefined;
  text?: string | undefined;
  template_id?: string | undefined;
  template_data?: { [k: string]: any | null } | undefined;
  tags?: { [k: string]: string } | undefined;
  attachments?: Array<Attachment$Outbound> | undefined;
  replyTo?: ReplyTo$Outbound | undefined;
};

/** @internal */
export const SendEmailRequest$outboundSchema: z.ZodMiniType<
  SendEmailRequest$Outbound,
  SendEmailRequest
> = z.pipe(
  z.object({
    from: z.string(),
    to: smartUnion([z.string(), z.array(z.string())]),
    subject: z.string(),
    html: z.optional(z.string()),
    text: z.optional(z.string()),
    templateId: z.optional(z.string()),
    templateData: z.optional(z.record(z.string(), z.nullable(z.any()))),
    tags: z.optional(z.record(z.string(), z.string())),
    attachments: z.optional(z.array(Attachment$outboundSchema)),
    replyTo: z.optional(ReplyTo$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      templateId: "template_id",
      templateData: "template_data",
    });
  }),
);

export function sendEmailRequestToJSON(
  sendEmailRequest: SendEmailRequest,
): string {
  return JSON.stringify(
    SendEmailRequest$outboundSchema.parse(sendEmailRequest),
  );
}
