/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SendBroadcastResponse = {
  success: boolean;
  sent: number;
  total: number;
};

/** @internal */
export const SendBroadcastResponse$inboundSchema: z.ZodMiniType<
  SendBroadcastResponse,
  unknown
> = z.object({
  success: types.boolean(),
  sent: types.number(),
  total: types.number(),
});

export function sendBroadcastResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendBroadcastResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendBroadcastResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendBroadcastResponse' from JSON`,
  );
}
