/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  Attachment,
  Attachment$Outbound,
  Attachment$outboundSchema,
} from "./attachment.js";
import {
  ReplyTo,
  ReplyTo$Outbound,
  ReplyTo$outboundSchema,
} from "./replyto.js";

export type To = string | Array<string>;

export type SendEmailRequest = {
  /**
   * Sender email. Required if not using a template with from_email set.
   */
  from?: string | undefined;
  to: string | Array<string>;
  /**
   * Email subject. Required if not using a template.
   */
  subject?: string | undefined;
  html?: string | undefined;
  text?: string | undefined;
  /**
   * Template ID. When provided, template values are used for subject, html, text, from, reply_to, and preview_text.
   */
  templateId?: string | undefined;
  /**
   * Variables to render in the template. Must include all variables defined in the template.
   */
  templateData?: { [k: string]: any | null } | undefined;
  tags?: { [k: string]: string } | undefined;
  attachments?: Array<Attachment> | undefined;
  replyTo?: ReplyTo | undefined;
  /**
   * Reply-To email address. Overrides template reply_to if provided.
   */
  replyToEmail?: string | undefined;
  /**
   * Preview text (preheader). Overrides template preview_text if provided.
   */
  previewText?: string | undefined;
};

/** @internal */
export type To$Outbound = string | Array<string>;

/** @internal */
export const To$outboundSchema: z.ZodMiniType<To$Outbound, To> = smartUnion([
  z.string(),
  z.array(z.string()),
]);

export function toToJSON(to: To): string {
  return JSON.stringify(To$outboundSchema.parse(to));
}

/** @internal */
export type SendEmailRequest$Outbound = {
  from?: string | undefined;
  to: string | Array<string>;
  subject?: string | undefined;
  html?: string | undefined;
  text?: string | undefined;
  template_id?: string | undefined;
  template_data?: { [k: string]: any | null } | undefined;
  tags?: { [k: string]: string } | undefined;
  attachments?: Array<Attachment$Outbound> | undefined;
  replyTo?: ReplyTo$Outbound | undefined;
  reply_to_email?: string | undefined;
  preview_text?: string | undefined;
};

/** @internal */
export const SendEmailRequest$outboundSchema: z.ZodMiniType<
  SendEmailRequest$Outbound,
  SendEmailRequest
> = z.pipe(
  z.object({
    from: z.optional(z.string()),
    to: smartUnion([z.string(), z.array(z.string())]),
    subject: z.optional(z.string()),
    html: z.optional(z.string()),
    text: z.optional(z.string()),
    templateId: z.optional(z.string()),
    templateData: z.optional(z.record(z.string(), z.nullable(z.any()))),
    tags: z.optional(z.record(z.string(), z.string())),
    attachments: z.optional(z.array(Attachment$outboundSchema)),
    replyTo: z.optional(ReplyTo$outboundSchema),
    replyToEmail: z.optional(z.string()),
    previewText: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      templateId: "template_id",
      templateData: "template_data",
      replyToEmail: "reply_to_email",
      previewText: "preview_text",
    });
  }),
);

export function sendEmailRequestToJSON(
  sendEmailRequest: SendEmailRequest,
): string {
  return JSON.stringify(
    SendEmailRequest$outboundSchema.parse(sendEmailRequest),
  );
}
