/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SendEmailResponse = {
  success: boolean;
  messageId: string;
  recipients: number;
};

/** @internal */
export const SendEmailResponse$inboundSchema: z.ZodMiniType<
  SendEmailResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    message_id: types.string(),
    recipients: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "message_id": "messageId",
    });
  }),
);

export function sendEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendEmailResponse' from JSON`,
  );
}
