/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Ports = {
  tls: number;
  ssl: number;
  tlsAlternative: number;
};

export type SmtpCredentials = {
  server: string;
  ports: Ports;
  username: string;
  password: string;
  encryption: string;
  note: string;
};

/** @internal */
export const Ports$inboundSchema: z.ZodMiniType<Ports, unknown> = z.pipe(
  z.object({
    tls: types.number(),
    ssl: types.number(),
    tls_alternative: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tls_alternative": "tlsAlternative",
    });
  }),
);

export function portsFromJSON(
  jsonString: string,
): SafeParseResult<Ports, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ports$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ports' from JSON`,
  );
}

/** @internal */
export const SmtpCredentials$inboundSchema: z.ZodMiniType<
  SmtpCredentials,
  unknown
> = z.object({
  server: types.string(),
  ports: z.lazy(() => Ports$inboundSchema),
  username: types.string(),
  password: types.string(),
  encryption: types.string(),
  note: types.string(),
});

export function smtpCredentialsFromJSON(
  jsonString: string,
): SafeParseResult<SmtpCredentials, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmtpCredentials$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmtpCredentials' from JSON`,
  );
}
