/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Profiles = {
  id: string;
  email: string;
  fullName: string | null;
  avatarUrl: string | null;
};

export type TeamMember = {
  id: string;
  organizationId: string;
  userId: string;
  role: string | null;
  createdAt: Date;
  profiles: Profiles | null;
};

/** @internal */
export const Profiles$inboundSchema: z.ZodMiniType<Profiles, unknown> = z.pipe(
  z.object({
    id: types.string(),
    email: types.string(),
    full_name: types.nullable(types.string()),
    avatar_url: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "full_name": "fullName",
      "avatar_url": "avatarUrl",
    });
  }),
);

export function profilesFromJSON(
  jsonString: string,
): SafeParseResult<Profiles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Profiles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Profiles' from JSON`,
  );
}

/** @internal */
export const TeamMember$inboundSchema: z.ZodMiniType<TeamMember, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      organization_id: types.string(),
      user_id: types.string(),
      role: types.nullable(types.string()),
      created_at: types.date(),
      profiles: types.nullable(z.lazy(() => Profiles$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "organization_id": "organizationId",
        "user_id": "userId",
        "created_at": "createdAt",
      });
    }),
  );

export function teamMemberFromJSON(
  jsonString: string,
): SafeParseResult<TeamMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamMember' from JSON`,
  );
}
