/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Template = {
  id: string;
  organizationId: string;
  name: string;
  subject: string;
  htmlContent: string | null;
  textContent: string | null;
  variables: Array<string> | null;
  createdBy: string | null;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Template$inboundSchema: z.ZodMiniType<Template, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    subject: types.string(),
    html_content: types.nullable(types.string()),
    text_content: types.nullable(types.string()),
    variables: types.nullable(z.array(types.string())),
    created_by: types.nullable(types.string()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "html_content": "htmlContent",
      "text_content": "textContent",
      "created_by": "createdBy",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function templateFromJSON(
  jsonString: string,
): SafeParseResult<Template, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Template$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Template' from JSON`,
  );
}
