/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UnsubscribeSettings = {
  id?: string | undefined;
  organizationId?: string | undefined;
  customMessage?: string | null | undefined;
  redirectUrl?: string | null | undefined;
  oneClickEnabled?: boolean | null | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const UnsubscribeSettings$inboundSchema: z.ZodMiniType<
  UnsubscribeSettings,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    organization_id: types.optional(types.string()),
    custom_message: z.optional(z.nullable(types.string())),
    redirect_url: z.optional(z.nullable(types.string())),
    one_click_enabled: z.optional(z.nullable(types.boolean())),
    created_at: types.optional(types.date()),
    updated_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "custom_message": "customMessage",
      "redirect_url": "redirectUrl",
      "one_click_enabled": "oneClickEnabled",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function unsubscribeSettingsFromJSON(
  jsonString: string,
): SafeParseResult<UnsubscribeSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnsubscribeSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnsubscribeSettings' from JSON`,
  );
}
