/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UpdateContactRequest = {
  email?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  subscribed?: boolean | undefined;
  metadata?: { [k: string]: any | null } | undefined;
};

/** @internal */
export type UpdateContactRequest$Outbound = {
  email?: string | undefined;
  first_name?: string | undefined;
  last_name?: string | undefined;
  subscribed?: boolean | undefined;
  metadata?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const UpdateContactRequest$outboundSchema: z.ZodMiniType<
  UpdateContactRequest$Outbound,
  UpdateContactRequest
> = z.pipe(
  z.object({
    email: z.optional(z.string()),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    subscribed: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.nullable(z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      firstName: "first_name",
      lastName: "last_name",
    });
  }),
);

export function updateContactRequestToJSON(
  updateContactRequest: UpdateContactRequest,
): string {
  return JSON.stringify(
    UpdateContactRequest$outboundSchema.parse(updateContactRequest),
  );
}
