/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UpdateOrganizationRequest = {
  name?: string | undefined;
  billingEmail?: string | undefined;
};

/** @internal */
export type UpdateOrganizationRequest$Outbound = {
  name?: string | undefined;
  billing_email?: string | undefined;
};

/** @internal */
export const UpdateOrganizationRequest$outboundSchema: z.ZodMiniType<
  UpdateOrganizationRequest$Outbound,
  UpdateOrganizationRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    billingEmail: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      billingEmail: "billing_email",
    });
  }),
);

export function updateOrganizationRequestToJSON(
  updateOrganizationRequest: UpdateOrganizationRequest,
): string {
  return JSON.stringify(
    UpdateOrganizationRequest$outboundSchema.parse(updateOrganizationRequest),
  );
}
