/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UpdateUnsubscribeSettingsRequest = {
  customMessage?: string | undefined;
  redirectUrl?: string | undefined;
  oneClickEnabled?: boolean | undefined;
};

/** @internal */
export type UpdateUnsubscribeSettingsRequest$Outbound = {
  custom_message?: string | undefined;
  redirect_url?: string | undefined;
  one_click_enabled?: boolean | undefined;
};

/** @internal */
export const UpdateUnsubscribeSettingsRequest$outboundSchema: z.ZodMiniType<
  UpdateUnsubscribeSettingsRequest$Outbound,
  UpdateUnsubscribeSettingsRequest
> = z.pipe(
  z.object({
    customMessage: z.optional(z.string()),
    redirectUrl: z.optional(z.string()),
    oneClickEnabled: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      customMessage: "custom_message",
      redirectUrl: "redirect_url",
      oneClickEnabled: "one_click_enabled",
    });
  }),
);

export function updateUnsubscribeSettingsRequestToJSON(
  updateUnsubscribeSettingsRequest: UpdateUnsubscribeSettingsRequest,
): string {
  return JSON.stringify(
    UpdateUnsubscribeSettingsRequest$outboundSchema.parse(
      updateUnsubscribeSettingsRequest,
    ),
  );
}
