/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UpdateDomainRequest = {
  receivingEnabled?: boolean | undefined;
};

/** @internal */
export type UpdateDomainRequest$Outbound = {
  receiving_enabled?: boolean | undefined;
};

/** @internal */
export const UpdateDomainRequest$outboundSchema: z.ZodMiniType<
  UpdateDomainRequest$Outbound,
  UpdateDomainRequest
> = z.pipe(
  z.object({
    receivingEnabled: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      receivingEnabled: "receiving_enabled",
    });
  }),
);

export function updateDomainRequestToJSON(
  updateDomainRequest: UpdateDomainRequest,
): string {
  return JSON.stringify(
    UpdateDomainRequest$outboundSchema.parse(updateDomainRequest),
  );
}
