/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UsageMetric = {
  id: string;
  organizationId: string;
  metricType: string;
  count: number;
  date: string;
  createdAt: Date;
};

/** @internal */
export const UsageMetric$inboundSchema: z.ZodMiniType<UsageMetric, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      organization_id: types.string(),
      metric_type: types.string(),
      count: types.number(),
      date: types.string(),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "organization_id": "organizationId",
        "metric_type": "metricType",
        "created_at": "createdAt",
      });
    }),
  );

export function usageMetricFromJSON(
  jsonString: string,
): SafeParseResult<UsageMetric, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageMetric$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageMetric' from JSON`,
  );
}
