/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Webhook = {
  id: string;
  organizationId: string;
  name: string;
  url: string;
  events: Array<string>;
  secret: string;
  active: boolean;
  createdBy: string | null;
  createdAt: Date;
};

/** @internal */
export const Webhook$inboundSchema: z.ZodMiniType<Webhook, unknown> = z.pipe(
  z.object({
    id: types.string(),
    organization_id: types.string(),
    name: types.string(),
    url: types.string(),
    events: z.array(types.string()),
    secret: types.string(),
    active: types.boolean(),
    created_by: types.nullable(types.string()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "created_by": "createdBy",
      "created_at": "createdAt",
    });
  }),
);

export function webhookFromJSON(
  jsonString: string,
): SafeParseResult<Webhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Webhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Webhook' from JSON`,
  );
}
