/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type WebhookDelivery = {
  id: string;
  webhookId: string;
  eventType: string;
  payload: { [k: string]: any | null };
  responseStatus: number | null;
  responseBody: string | null;
  attemptCount: number;
  deliveredAt: Date | null;
  createdAt: Date;
};

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    webhook_id: types.string(),
    event_type: types.string(),
    payload: z.record(z.string(), types.nullable(z.any())),
    response_status: types.nullable(types.number()),
    response_body: types.nullable(types.string()),
    attempt_count: types.number(),
    delivered_at: types.nullable(types.date()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "webhook_id": "webhookId",
      "event_type": "eventType",
      "response_status": "responseStatus",
      "response_body": "responseBody",
      "attempt_count": "attemptCount",
      "delivered_at": "deliveredAt",
      "created_at": "createdAt",
    });
  }),
);

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}
