/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type WebhookToggleResponse = {
  success: boolean;
  active: boolean;
};

/** @internal */
export const WebhookToggleResponse$inboundSchema: z.ZodMiniType<
  WebhookToggleResponse,
  unknown
> = z.object({
  success: types.boolean(),
  active: types.boolean(),
});

export function webhookToggleResponseFromJSON(
  jsonString: string,
): SafeParseResult<WebhookToggleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookToggleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookToggleResponse' from JSON`,
  );
}
